#!/usr/bin/env python
# write plate.txt files for batch 152
import os

plate_data = {
    '0807e24c': 'equip zone sprite dispatch function. Routes by IWRAM state code ([0x0201b290+0x94*8]): 0x80=activate equip zone sprite (iterate effect slots, for zone_type=0xe call enqueue_equip_zone_sprite_by_slot_ptr, count in [0x0201b290+0x4a4]); 0x7f=check spell zone placeable then call increment_lp_bar_display_counter; other=return 0. Side effects: [IWRAM+0x4a4]+=1 (per sprite, activate path only); OAM sprite buffer via enqueue_equip_zone_sprite_by_slot_ptr. Constants: STATE_ACTIVATE=0x80, STATE_CHECK=0x7f, IWRAM_BASE=0x0201b290, state_offset=0x4a0 (0x94*8), IWRAM_SPRITE_COUNT=[IWRAM_BASE+0x4a4], gDuelFieldSlots=0x0201c510, PLAYER_STRIDE=0x868.',
    '0807e5a4': 'Driven by submit_lp_indicator_with_slot_xor_flag and enqueue_sprite_attr_type11 call chain. Takes effect node ptr (r0=r4), extracts player_id (bit0 of byte[+2], xor inverted), calls submit_lp_indicator_with_slot_xor_flag with player_id_inv and r2=0xfa*2=0x1f4. If return nonzero, calls enqueue_sprite_attr_type11 with [r4+0]=card_id halfword, r0=0, r2=1, r3=0 to write LP sprite attr. Side effects: submit LP indicator via submit_lp_indicator_with_slot_xor_flag; write OAM sprite type11 via enqueue_sprite_attr_type11. Constants: LP_INDICATOR_PARAM=0xfa*2=0x1f4 (r2), SPRITE_TYPE11_MODE=1 (r2 arg).',
    '0807efec': 'Dispatches Banisher of the Light equip zone sprite or LP indicator based on IWRAM state code ([0x0201b290+0x94*8]). 0x80 path: clear [IWRAM+0x4a4]; read equip display slot ptr from gP1LifePoints[player_id*0x868+0xc]; if nonzero call dispatch_equip_zone_sprite_banisher_by_field_count with r2=0; [IWRAM+0x4a4]+=1; return 0x7f. 0x7e path: call count_field_copies_of_card(0x1332=Banisher of the Light); if no copies call submit_lp_indicator_with_slot_xor_flag(player_id_inv, card_id_copy_count*0xc8). 0x7f path: increment_lp_bar_display_counter; clear [IWRAM+0x4a4]; return 0x7f. Side effects: [IWRAM+0x4a4] write (0 or +=1); OAM sprite via dispatch_equip_zone_sprite_banisher_by_field_count. Constants: STATE_80=0x80, STATE_7F=0x7f, STATE_7E=0x7e, CARD_ID_BANISHER=0x1332 (Banisher of the Light), LP_COUNT_SCALE=0xc8, gP1LifePoints=0x0201c4e0, PLAYER_STRIDE=0x868, IWRAM_BASE=0x0201b290, counter_offset=0x4a4.',
    '0807f158': 'Two-step operation: enqueue_field_slot_sprite_with_state_update and test_equip_target_slot_zone11. r1=effect_node_ptr (via .hword 0x4647=mov r7,lr + .hword 0x4680=mov r8,r0), r0=caller-set ptr. First reads from gDuelFieldSlots (0x0201c510) indexed by [byte2] player_id and slot_idx to compute two zone entry addrs; extracts tile_col_count (bits[9:2]) and flip_bit (bit14); compares tile_col_count*2+flip_bit with slot[+4] bits[7:1] (capacity); if equal calls enqueue_field_slot_sprite_with_state_update(player_id, slot_idx, tile_col_count); then re-extracts player_id/slot_idx and calls test_equip_target_slot_zone11. Side effects: write state and enqueue OAM sprite via enqueue_field_slot_sprite_with_state_update; run zone11 equip target check via test_equip_target_slot_zone11. Constants: gDuelFieldSlots=0x0201c510, PLAYER_STRIDE=0x868, BYTE4_FLAGS: bit1-7=capacity, bit8=mark.',
    '0807f1ec': 'Sibling function of enqueue_field_slot_sprite_for_zone11 (0x0807f158) with identical structure. Only difference: final call is dispatch_slot_sprite_attr_with_equip_head_flag instead of test_equip_target_slot_zone11. r1=effect_node_ptr, r0=caller-set context ptr. Also writes [r7+4] OR 0x2|0x4|0x8 state bits; reads from gDuelFieldSlots; compares tile_col_count with capacity; if equal calls enqueue_field_slot_sprite_with_state_update; then extracts player_id/slot_idx with r3=0 and calls dispatch_slot_sprite_attr_with_equip_head_flag. Side effects: [r7+4] strb OR bits 1/2/3; OAM sprite via enqueue_field_slot_sprite_with_state_update; equip head sprite via dispatch_slot_sprite_attr_with_equip_head_flag. Constants: gDuelFieldSlots=0x0201c510, PLAYER_STRIDE=0x868.',
    '0807f458': 'Dispatches equip zone sprite (shape_b variant) based on IWRAM state code ([DWORD_0807f48c=0x0201b290+0x4a4]). 0x80 path: clear [IWRAM+0x4a4]; call increment_lp_bar_display_counter; return 0x7f. 0x7f path: check gP1LifePoints for slot entry at +0x1c*player_id; if nonzero call enqueue_equip_zone_sprite_attr_shape_b(player_id, slot_ptr, attr1_val), return 0x7e; if zero call enqueue_lp_counter_sprite_by_player, return 0x7d. 0x7e path: check [IWRAM+0x4a4] > 1; if so call decrement_lp_bar_display_counter; else return 0x7f. 0x7d path: [IWRAM+0x4a4]+=1; if <=1 return 0x7f; else decrement. Side effects: [0x0201b290+0x4a4] write; OAM sprite via enqueue_equip_zone_sprite_attr_shape_b. Constants: STATE_80/7F/7E/7D=0x80/0x7f/0x7e/0x7d, gP1LifePoints=0x0201c4e0, OFFSET_0x1ce8=0x1ce8, IWRAM_BASE=0x0201b290, IWRAM_COUNTER_OFFSET=0x4a4, PLAYER_STRIDE=0x868, ZONE_ENTRY_OFFSET=0x5cc.',
    '0807f644': 'Checks whether card_id (r0) satisfies equip display criteria. Three-stage check: (1) card_id==0x157e: calls get_card_extended_stat_field6(r1=card_ptr); returns 1 if field6==1, else 0. (2) card_id==0x19ef (Elemental Hero Erikshieler): checks four criteria_code values (0x18a6=EHero Avian, 0x18a7=Burstinatrix, 0x18a8=Clayman, 0x18f9=Bubbleman) via check_card_equip_criteria_by_ext_field6; returns 1 on any match. (3) Other card_id: calls find_equip_display_entry_by_card_id in ROM table; on entry found uses entry[+2/+4/+6] three criteria_code values; returns 1 on any match. Returns 0 if not found or no match. No side effects. Constants: CARD_ID_A=0x157e, CARD_ID_ERIKSHIELER=0x19ef, CRITERIA_AVIAN=0x18a6, CRITERIA_BURSTINATRIX=0x18a7, CRITERIA_CLAYMAN=0x18a8, CRITERIA_BUBBLEMAN=0x18f9.',
    '0807f6f0': 'Returns equip display type code [0..5] based on card_id (r0). 0x157e: return 5. 0x19ef (Elemental Hero Erikshieler): return 4. Other: call find_equip_display_entry_by_card_id; if not found return 0; if found and entry[+6]==0 return 2, else return 3. Return value used by FUN_0807f7bc and other equip slot dispatch functions to select enqueue path: 0=no display entry, 2/3/4/5=different display types. No side effects. Constants: CARD_ID_A=0x157e->TYPE_5=5, CARD_ID_ERIKSHIELER=0x19ef->TYPE_4=4, TYPE_NO_ENTRY=0, TYPE_ENTRY_NO_FIELD6=2, TYPE_ENTRY_HAS_FIELD6=3.',
    '0807f730': 'Returns equip display criteria_code (u16) based on card_id (r0) and slot_index (r1=r4). 0x157e: return 1 (any slot). 0x19ef (Elemental Hero Erikshieler): by slot_index: 0->0x18a6(EHero Avian), 1->0x18a7(Burstinatrix), 2->0x18a8(Clayman), 3->0x18f9(Bubbleman); slot>=4 returns 0. Other card_id: call find_equip_display_entry_by_card_id; not found returns 0; found: slot 0->entry[+2], 1->entry[+4], 2->entry[+6]; slot>=3 returns 0. FUN_0807f7bc calls this to write criteria_code into [IWRAM+0x5ac+idx*4]. No side effects. Constants: CARD_ID_A=0x157e->TYPE_FIXED=1, CARD_ID_ERIKSHIELER=0x19ef, slot0=0x18a6, slot1=0x18a7, slot2=0x18a8, slot3=0x18f9, MAX_SLOT_GENERIC=2.',
    '0807f800': 'Iterates equip slot criteria array ([IWRAM+0x5ac], count=[IWRAM+0xb4*8]); for each criteria_code calls check_card_equip_criteria_by_ext_field6(criteria_code, card_stat_ptr); returns 1 on any match, 0 if none. Called by FUN_0807f974 and FUN_08080348 equip activation check functions. No side effects. Constants: IWRAM_BASE=0x0201b290, CRITERIA_ARRAY_OFFSET=0x5ac, COUNT_OFFSET=0xb4*8=0x5a0.',
    '0807f848': 'Iterates equip slot criteria array ([IWRAM+0x5ac], count=[IWRAM+0xb4*8]); for each criteria_code calls check_slot_card_equip_criteria_by_state_code(criteria_code, slot_ptr=r6, card_ptr=r5); returns 1 on any match, 0 if none. Symmetric to check_equip_slot_criteria_by_ext_field6_any (0x0807f800) but uses state_code path. Entry .hword 0x4688=mov r8,r1 saves IWRAM base. No side effects. Constants: IWRAM_BASE=0x0201b290, CRITERIA_ARRAY_OFFSET=0x5ac, COUNT_OFFSET=0xb4*8=0x5a0.',
    '0807f89c': 'Iterates equip slot criteria array ([IWRAM+0x5ac], count=[IWRAM+0xb4*8]); for each criteria_code calls check_card_equip_criteria_by_ext_field6(criteria_code, slot_card_ptr=r6); on match clears that criteria slot ([IWRAM+0x5ac+idx*4]=0) and returns 1. Returns 0 if no match. Symmetric to check_equip_slot_criteria_by_ext_field6_any but with clear-on-match side effect. Entry .hword 0x4690=mov r8,r2. Side effects: [0x0201b290+0x5ac+matched_idx*4]:=0 (on match). Constants: IWRAM_BASE=0x0201b290, CRITERIA_ARRAY_OFFSET=0x5ac, COUNT_OFFSET=0xb4*8=0x5a0.',
    '0807f8f0': 'Iterates equip slot criteria array; finds first match via check_slot_card_equip_criteria_by_state_code; clears found slot [r9+0x5ac+found_idx*4]=0; returns 1 on any match, 0 if none. Differs from clear_equip_slot_criteria_on_ext_field6_match (0x0807f89c): uses state_code path; continues after first match before clearing. Entry saves multiple high regs (.hword 0x464f=mov r7,r9; .hword 0x4646=mov r6,r8; .hword 0x4680=mov r8,r0); r6 init=-1 sentinel (movs r6,#1; rsbs r6,r6,#0). Side effects: [r9+0x5ac+found_idx*4]:=0 (first match). Constants: IWRAM_BASE=0x0201b290, CRITERIA_ARRAY_OFFSET=0x5ac, COUNT_OFFSET=0xb4*8=0x5a0.',
    '08080c9c': 'Compound operation: (1) call assemble_effect_slot_attr_with_zone_lookup(r5,r6,r4) to assemble equip slot attr; (2) call enqueue_equip_slot_sprite_by_player(player_id, slot_idx) to write OAM sprite; (3) extract bits[16:15] (display_code) from [r5+4], +1 AND 0x7, write back to bits[17:15]; (4) if slot_idx<=4 and entry[+8] (ldrh) nonzero and entry card_id is 0x1596 or 0x1598, call enqueue_sprite_attr_with_mode with mode=2 for conditional sprite. Used by 20+ equip state machine callers. Side effects: [r5+4] bits[17:15]:=(old+1)&7 (display_code rotate); OAM sprite via enqueue_equip_slot_sprite_by_player; conditional OAM sprite via enqueue_sprite_attr_with_mode. Constants: DISPLAY_CODE_MASK=0xfffc7fff, PLAYER_STRIDE=0x868, gDuelFieldSlots=0x0201c510, SPECIAL_ID_A=0x1596, SPECIAL_ID_B=0x1598, MAX_SLOT_IDX=4.',
    '08080d28': 'Compound operation: (1) call pack_effect_slot_attr_with_type_flags(r0, player_id, slot_idx, display_code) to pack attr and get effect node ptr; (2) call enqueue_equip_slot_sprite_with_display_code(player_id, slot_idx, display_code) to write OAM sprite; (3) read effect node ptr [+4] display_code bits[16:15], +1 AND 0x7, write back to bits[17:15] (same display_code rotate as 08080c9c). Entry .hword 0x4646=mov r6,r8; r1/r2/r3 saved to r4/r5/r6; .hword 0x4640=mov r8,r0 gets effect node ptr. Side effects: [effect_node_ptr+4] bits[17:15]:=(old+1)&7 (display_code rotate); OAM sprite via enqueue_equip_slot_sprite_with_display_code. Constants: DISPLAY_CODE_MASK=0xfffc7fff.',
    '08080ea0': 'Large card_id dispatch hub (indeg=2, game_str/card_ids/duel_field context). Reads effect struct [+0] u16 card_id (ldrh r1,[r5,#0]); uses binary search tree in ROM to find display op handler stub and tail-jump. Each branch calls a prenamed trigger_card_display_op_0xNN stub (0x5f/0x62/0x63/0x64/0x66/0x6b/0x6c/0x6d/0x6e/0x6f/0x76/0x77/0x78/0x7a/0x80/0x112/0x119 etc.). Also has trigger_card_display_op_by_equip_type (0x1298=Cyber Raider) for equip type sub-dispatch. sp allocated via add sp,r4 (r4=0xfffffe00, 0x200 bytes) for game_str format buffer. Side effects: card display op state (IWRAM) via trigger_card_display_op31_if_not_active. Constants: SP_FRAME=0x200 (r4=0xfffffe00), first check card_id=0x15a8->trigger_card_display_op_0x119, card_id=0x13ab->trigger_card_display_op_0x77.',
    '08081ce8': 'Drives equip effect slot display state machine. Reads [0x0201b290+0x96*8] (IWRAM state counter) and branches: =0 (first tick): reads equip slot link head from [0x0201e2a0+player_id*4+8]; if valid writes [gP1LifePoints+0xea*0x20=0x1d40]:=0; calls invoke_card_display_op_0x31_sub3_with_packed_params with r0=0x67, r1=0xcb*2=0x196, r2=0x197, r3=0; [IWRAM+0x96*8]+=1. =1 (second tick): reads equip ptr from [gP1LifePoints+0x1d40], extracts player_id, xors with r6; calls push_to_effect_slot_array(effect_ptr, player_xor_r6); calls set_lp_display_row_type15; [IWRAM+0x96*8]+=1. >=2: return 1 (done). Side effects: [0x0201b290+0x4b0] state counter; [gP1LifePoints+0x1d40]:=0 (state=0); effect slot array push; card display op invoke. Constants: IWRAM_BASE=0x0201b290, STATE_OFFSET=0x96*8=0x4b0, EQUIP_LINK_BASE=0x0201e2a0, gP1LifePoints=0x0201c4e0, LP_AREA_OFFSET=0xea*0x20=0x1d40, sub3_r0=0x67, r1=0xcb*2=0x196, r2=0x197.',
    '08081d9c': 'Extracts player_id from effect node ptr (r0), byte[+2] bit0; calls push_to_effect_slot_array(r0=effect_node_ptr, r1=player_id); returns 1 always. Leaf wrapper encapsulating player_id extraction + push_to_effect_slot_array pattern. Used by push_to_effect_slot_array call chain (0x08080b74 hub). Side effects: via push_to_effect_slot_array: effect slot array write.',
    '08081db0': 'Extracts player_id from effect node ptr (r0), byte[+2] bit0; inverts to opponent_id = 1 - player_id; calls push_to_effect_slot_array with r1=opponent_id; returns 1 always. Only difference from push_effect_slot_by_player_from_node (0x08081d9c): passes opponent side (1-player_id) instead of player side. Side effects: via push_to_effect_slot_array: effect slot array write (opponent side).',
    '08082e98': 'Executes three-path equip LP display operation based on IWRAM state code ([0x0201b290+0x96*8]). =0 path: clear bits[17:0] from [r5+4] (AND 0xfffc7fff); clear bits[4:0] from [r5+6] (AND ~0x1d); call set_lp_row_type10_with_value with player_id/card_id; [IWRAM+0x96*8]+=1; return 0. =1 path: extract player_id/slot_idx from [r5+2]; read LP halfword from [gP1LifePoints+0x1da8]; call enqueue_sprite_attr_with_xy_split(player_id, slot_idx, LP_halfword); call push_to_effect_slot_array; [IWRAM+0x96*8]+=1; return 0. =2 path: extract opponent_id; read LP halfword; call set_lp_display_row_type15 with r1=0x1357=TYPE15_PARAM, r2=LP_halfword; [IWRAM+0x96*8]+=1; return 0. Other: return 1 (done). Side effects: [r5+4] AND 0xfffc7fff (state=0); [r5+6] AND ~0x1d (state=0); OAM sprite via enqueue_sprite_attr_with_xy_split (state=1); effect slot push via push_to_effect_slot_array (state=1); LP row update via set_lp_display_row_type15 (state=2); [0x0201b290+0x4b0]+=1. Constants: IWRAM_BASE=0x0201b290, STATE_OFFSET=0x96*8=0x4b0, gP1LifePoints=0x0201c4e0, LP_OFFSET=0x1da8, TYPE15_PARAM=0x1357, ATTR_CLEAR_MASK=0xfffc7fff, BYTE6_CLEAR_MASK=~0x1d=0xe2.',
}

base = 'E:/Workspace/yugioh-ex2006-re/doc/dev/eval'
ok = 0
for addr, text in plate_data.items():
    non_ascii = [c for c in text if ord(c) > 127]
    if non_ascii:
        print('NON-ASCII in %s: %s' % (addr, non_ascii))
        continue
    fname = os.path.join(base, addr + '.plate.txt')
    with open(fname, 'w', encoding='ascii') as f:
        f.write(text)
    ok += 1
    print('OK %s (%d chars)' % (addr, len(text)))

print('Total written:', ok)
