"""
Encoder: text/card-desc/{ja,en,de,fr,it,es}.txt → data/card-descriptions.s

Pipeline (build-time):
  txt sources → bytes → octal-escape .ascii lines → assembled binary

编码规则:
  ja: char → codetable idx → (hi=0xF0|(idx>>7), lo=0x80|(idx&0x7F)) 2 byte;
      未在 codetable 的 char (如 @, +, 数字 等) → 1 byte ASCII;
      末尾固定加 \0\0
  en/de/fr/it/es: char → CP1252 单字节; 末尾 payload + \0 + (\0 若总长奇)

输出格式:
  - .ascii "..." (octal escape) 一条 entry 一行
  - cid 顺序与源 .s 保持一致
  - 包含 desc_offsets macro + pointer table
  - label 使用 _ja (替代旧 _xx)
"""
import re
import json
from pathlib import Path

SRC_DIR = Path('text/card-desc')
OUT_PATH = Path('data/card-descriptions.s')

# Load codetable (idx → char) and reverse (char → idx)
CT = {int(k): v for k, v in json.loads(
    open('tools/jp-decode/codetable.json', encoding='utf-8').read()
)['by_idx'].items()}
# 控制字节字符: 这些 ASCII 字符在 _ja 数据中作为单字节控制码出现, 不能走 codetable
# 0x40='@' (出现于 @4/@5/@7 控制序列), 0x34/0x35/0x37 为后缀数字字符
CONTROL_ASCII = {'@', '4', '5', '7'}

# 训练好的 char → 默认 idx (基于 _ja 数据中最高频 idx 分配)
char_to_idx = json.loads(
    open('tools/card-desc/char_to_idx.json', encoding='utf-8').read()
)


def encode_ja(text):
    """text → bytes. char_to_idx is strictly 1-to-1, so simple lookup;
    chars not in mapping (@, 4, 5, 7) pass through as ASCII bytes."""
    out = bytearray()
    for ch in text:
        idx = char_to_idx.get(ch)
        if idx is not None:
            hi = ((idx >> 7) & 0xF) | 0xF0
            lo = (idx & 0x7F) | 0x80
            out.append(hi)
            out.append(lo)
        else:
            cp = ord(ch)
            if cp > 0xFF:
                raise ValueError(f'char {ch!r} (U+{cp:04X}) not in codetable, not ASCII')
            out.append(cp)
    out.extend(b'\x00\x00')
    return bytes(out)


def encode_lang(text):
    """text → bytes per CP1252 + alignment padding."""
    payload = text.encode('cp1252')
    out = bytearray(payload)
    out.append(0)
    if len(out) % 2 != 0:
        out.append(0)
    return bytes(out)


def to_octal_ascii(bs):
    """bytes → GAS .ascii string body (no quotes)."""
    parts = []
    for b in bs:
        if b == 0x22:
            parts.append(r'\"')
        elif b == 0x5C:
            parts.append(r'\\')
        elif 0x20 <= b < 0x7F:
            parts.append(chr(b))
        else:
            parts.append(f'\\{b:03o}')
    return ''.join(parts)


def parse_txt(path):
    """parse src .txt → dict[cid → text].

    Format:
      =NNNN=
      <text content lines until next =NNNN= or EOF>
      <blank line>
    """
    content = open(path, encoding='utf-8').read()
    # Split on lines starting with =NNNN=
    entries = {}
    pat = re.compile(r'^=(\d{4})=\s*\n', re.MULTILINE)
    matches = list(pat.finditer(content))
    for i, m in enumerate(matches):
        cid = int(m.group(1))
        body_start = m.end()
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        body = content[body_start:body_end]
        # 移除末尾空行 (但保留中间换行)
        body = body.rstrip('\n')
        entries[cid] = body
    return entries


# Parse 6 lang sources
LANGS = ['ja', 'en', 'de', 'fr', 'it', 'es']
all_entries = {}  # cid → {lang → text}
for lang in LANGS:
    txt_path = SRC_DIR / f'{lang}.txt'
    entries = parse_txt(txt_path)
    print(f'{lang}.txt: {len(entries)} entries')
    for cid, text in entries.items():
        all_entries.setdefault(cid, {})[lang] = text

cids = sorted(all_entries.keys())
print(f'\nTotal cids: {len(cids)} (range {cids[0]}..{cids[-1]})')

# 检查每条 6 lang 齐全
for cid in cids:
    missing = [l for l in LANGS if l not in all_entries[cid]]
    if missing:
        raise SystemExit(f'cid={cid} missing langs: {missing}')

# Encode all
print('\nEncoding...')
enc = {}  # (cid, lang) → bytes
for cid in cids:
    for lang in LANGS:
        text = all_entries[cid][lang]
        if lang == 'ja':
            enc[(cid, lang)] = encode_ja(text)
        else:
            enc[(cid, lang)] = encode_lang(text)
total_bytes = sum(len(b) for b in enc.values())
print(f'Encoded {len(enc)} labels, total {total_bytes:,} B')

# Output .s
with open(OUT_PATH, 'w', encoding='utf-8', newline='\n') as f:
    f.write('@ =============================================================================\n')
    f.write('@ Card Descriptions (merged: effect-text + special-card text)\n')
    f.write('@ ROM 0x15FFF0C - 0x18169B8  (2,189,996 B)\n')
    f.write('@\n')
    f.write('@  1. card_descs_table   0x15FFF0C - 0x180A508  (2,139,644 B)\n')
    f.write('@     2098 cards x 6 langs (JA/EN/DE/FR/IT/ES), null-terminated\n')
    f.write('@  2. card_desc_pointer_table        0x180A508 - 0x18169B8  (50,352 B, cid=0..2097)\n')
    f.write('@     Last u32 high 2B byte-overlaps with card_stats[0].zero0 (=0x0020).\n')
    f.write('@\n')
    f.write('@ Generated by tools/card-desc/encode_txt_to_s.py from text/card-desc/*.txt\n')
    f.write('@ DO NOT EDIT directly — edit the .txt sources and re-run encoder.\n')
    f.write('@ =============================================================================\n\n')

    f.write('@ Macro: 6 lang offsets for cid (label - pool)\n')
    f.write('.macro desc_offsets cid\n')
    for lang in LANGS:
        f.write(f'\t.word card_desc_\\cid\\()_{lang} - card_descs_table\n')
    f.write('.endm\n\n')

    f.write('@ -----------------------------------------------------------------------------\n')
    f.write(f'@ 1. Text Pool (2098 cards x 6 langs, null-terminated, 2-byte aligned)\n')
    f.write('@    ROM 0x15FFF0C - 0x180A508  (2,139,644 B)\n')
    f.write('@ -----------------------------------------------------------------------------\n')
    f.write('card_descs_table:\n')

    for cid in cids:
        for lang in LANGS:
            bs = enc[(cid, lang)]
            f.write(f'card_desc_{cid:04d}_{lang}:\n')
            f.write(f'\t.ascii "{to_octal_ascii(bs)}"\n')

    # Pointer table from metadata
    f.write('\n@ -----------------------------------------------------------------------------\n')
    f.write('@ 2. Pointer Table (cid=0..2097), 6 u32 per cid\n')
    f.write('@    44 cids are alt-art entries that point to a different label_cid.\n')
    f.write('@ -----------------------------------------------------------------------------\n')
    f.write('card_desc_pointer_table:\n')
    pt_path = SRC_DIR / 'pointer-table.txt'
    pt_pat = re.compile(r'^(\d{4})\s+(\d{4})\s+(.*)$')
    with open(pt_path, encoding='utf-8') as ptf:
        for line in ptf:
            line = line.rstrip('\n')
            if not line or line.startswith('@'):
                continue
            m = pt_pat.match(line)
            if not m:
                continue
            cid = m.group(1)
            label_cid = m.group(2)
            comment = m.group(3)
            f.write(f'\tdesc_offsets {label_cid}    @ card id: {int(cid)}, {comment}\n')

print(f'\nwrote {OUT_PATH}')
