"""build_remap_table.py — 生成 data/game-strings-remap-table.s

game string ID -> row 索引表 @ ROM 0x250, 1651 x u16 (单调递增):
- game_str_id_to_row 对其二分查找 (输入 string ID -> 输出 master 表 row)
- count 在 0x240 (game_str_id_remap_count = 1651), 仍 inline 于 asm/all.s
- 0x242..0x24f 为 14 B 零填充 (位于 count 与 table 之间)

值为定长 u16 字符串 ID (固定搜索键, 非位置偏移), 故直接从 ROM 原样导出。
asm/all.s 通过 .include 引用此文件; ExportRangeToGas.py 的 SKIP_REGIONS 配置使其
跳过 0x08000242..0x08000F36 区段。byte-identical 由 build 验证。
"""
import struct
from pathlib import Path

ROM_PATH = Path('roms/2343.gba')
OUT_PATH = Path('data/game-strings-remap-table.s')
PAD_START = 0x242          # count(0x240) 后游标落点; 14 B 零填充
TABLE_START = 0x250
N = 1651
PAD_LEN = TABLE_START - PAD_START   # 0xe


def main():
    rom = ROM_PATH.read_bytes()
    pad = rom[PAD_START:TABLE_START]
    assert all(b == 0 for b in pad), 'expected 14 zero bytes at 0x242'
    vals = [struct.unpack_from('<H', rom, TABLE_START + 2 * i)[0] for i in range(N)]
    end = TABLE_START + 2 * N
    assert end == 0xF36, hex(end)

    out = [
        '@ data/game-strings-remap-table.s',
        '@ game string ID -> row 索引表 (game_str_id_to_row 二分查找用)',
        '@ ROM 0x242 ~ 0xF36  (14B 零填充 + %d x u16 单调递增)' % N,
        '@ count 在 0x240 (game_str_id_remap_count=%d, 仍 inline 于 asm)' % N,
        '@ Generated by tools/game-strings/build_remap_table.py (源: roms/2343.gba @0x250)',
        '@ 引用本表的代码: asm 字面量池 .word game_str_id_remap_table (0x08000250)',
        '',
        '\t.zero  0x%x                            @ 0x242..0x24f 填充' % PAD_LEN,
        'game_str_id_remap_table:',
    ]
    for i in range(0, N, 8):
        out.append('\t.hword ' + ', '.join('0x%04x' % v for v in vals[i:i + 8]))

    OUT_PATH.write_text('\n'.join(out) + '\n', encoding='utf-8', newline='\n')
    print('[ok] %s (%d hwords + %dB zero pad)' % (OUT_PATH, N, PAD_LEN))


if __name__ == '__main__':
    main()
