"""build_pointer_table.py — 生成 data/game-strings-pointer-table.s

Master pointer table @ ROM 0xF40, 1651 行 x 24 B:
- 每行 6 x u32 = [JA, EN, DE, FR, IT, ES] offset (相对 game_str_ja = STRING_TABLE_BASE)
- 全部 row 用 label 减法表达 (label - game_str_ja)
- Rows 0..1641: 共享 6 lang UI 文本
- Rows 1642..1650: Death Message 尾巴
  · JA col: 真实日文 (Death Message description + 4 kanji + 4 hiragana)
  · 5 lang col: ptr → \\0\\0 (各 lang 自己 region 末的 9 个 \\0\\0 槽)
- 末尾 8 字节 \\0 alignment pad

asm/all.s 通过 .include 引用此文件 (替代原 ROM_INCBIN 0xf44, 0x9acc 内联数据).
ExportRangeToGas.py 的 SKIP_REGIONS 配置使其跳过 0x08000F40..0x0800AA10 区段.
"""
from pathlib import Path

OUT_PATH = Path('data/game-strings-pointer-table.s')

TABLE_START = 0xF40
N_ROWS = 1651
TRAILING_PAD = 8


def main():
    end_addr = TABLE_START + N_ROWS * 24 + TRAILING_PAD

    lines = []
    lines.append('@ data/game-strings-pointer-table.s')
    lines.append('@ Master pointer table for game-strings')
    lines.append(f'@ ROM 0x{TABLE_START:X} ~ 0x{end_addr:X}  '
                 f'({N_ROWS} rows x 24 B + {TRAILING_PAD} B trailing pad)')
    lines.append('@ Generated by tools/game-strings/build_pointer_table.py')
    lines.append('@')
    lines.append('@ 每行 6 x u32 = [JA, EN, DE, FR, IT, ES] offset (相对 game_str_ja = STRING_TABLE_BASE)')
    lines.append('@ Rows 0..1641: 共享 6 lang UI 文本')
    lines.append('@ Rows 1642..1650: Death Message 尾巴 (JA 真实日文; 5 lang 各 region 末 \\0\\0)')
    lines.append('@')
    lines.append('@ 引用本文件的代码: asm/all.s 字面量池 0x08000F40 (101 hits)')
    lines.append('')
    lines.append('@ ----------------------------------------------------------------------')
    lines.append('@ Macro: 6 lang offsets for one row (label - base)')
    lines.append('.macro gst_offsets row')
    lines.append('\t.word game_str_ja_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_en_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_de_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_fr_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_it_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_es_\\row\\() - game_str_ja')
    lines.append('.endm')
    lines.append('')
    lines.append('@ ----------------------------------------------------------------------')
    lines.append('game_str_pointer_table:')
    for r in range(N_ROWS):
        lines.append(f'\tgst_offsets {r:04d}')

    lines.append('')
    lines.append(f'@ 表末 alignment pad ({TRAILING_PAD} bytes)')
    lines.append(f'\t.zero {TRAILING_PAD}')

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    total_bytes = N_ROWS * 24 + TRAILING_PAD
    print(f'wrote {OUT_PATH}')
    print(f'  {N_ROWS} rows x 24 B + {TRAILING_PAD} B pad = {total_bytes} B')
    print(f'  ROM range: 0x{TABLE_START:05X} ~ 0x{end_addr:05X}')


if __name__ == '__main__':
    main()
else:
    main()
