"""build_pointer_table.py — 生成 data/game-strings-pointer-table.s

Master pointer table @ ROM 0xF40, 1651 行 x 24 B (1642 共享 + 9 JA-only):
- 行 0..1641: 6 lang offset 全有效, 用 label 减法 (label - game_str_ja)
- 行 1642..1650: JA-only Death Message extras, 5 lang col 是 phantom 占位
  (ptr 落在各 lang region 末尾后, 仅作字节占位; 其值从 ROM 直读硬编码)
- 末尾 8 字节 \\0 alignment pad

asm/all.s 通过 .include 引用此文件 (替代原 ROM_INCBIN 0xf44, 0x9acc 内联数据).
ExportRangeToGas.py 的 SKIP_REGIONS 配置使其跳过 0x08000F40..0x0800AA10 区段.
"""
import struct
from pathlib import Path

ROM_PATH = 'roms/2343.gba'
OUT_PATH = Path('data/game-strings-pointer-table.s')

TABLE_START = 0xF40
N_SHARED_ROWS = 1642   # rows 0..1641, 6 lang 全有效
N_EXTRA_ROWS = 9       # rows 1642..1650, JA-only (5 lang col 是 phantom)
N_TOTAL_ROWS = N_SHARED_ROWS + N_EXTRA_ROWS  # 1651
TRAILING_PAD = 8       # 0xAA08..0xAA10 alignment pad


def main():
    rom = open(ROM_PATH, 'rb').read()
    end_addr = TABLE_START + N_TOTAL_ROWS * 24 + TRAILING_PAD  # = 0xAA10

    lines = []
    lines.append('@ data/game-strings-pointer-table.s')
    lines.append('@ Master pointer table for game-strings')
    lines.append(f'@ ROM 0x{TABLE_START:X} ~ 0x{end_addr:X}  '
                 f'({N_TOTAL_ROWS} rows x 24 B + {TRAILING_PAD} B trailing pad)')
    lines.append('@ Generated by tools/game-strings/build_pointer_table.py')
    lines.append('@')
    lines.append('@ 每行 6 x u32 = [JA, EN, DE, FR, IT, ES] offset (相对 game_str_ja = STRING_TABLE_BASE)')
    lines.append('@ Rows 0..1641: 共享 6 lang')
    lines.append('@ Rows 1642..1650: JA-only Death Message extras (5 lang col 是 phantom 占位)')
    lines.append('@')
    lines.append('@ 引用本文件的代码: asm/all.s 字面量池 0x08000F40 (101 hits)')
    lines.append('')
    lines.append('@ ----------------------------------------------------------------------')
    lines.append('@ Macro: 6 lang offsets for shared row (label - base)')
    lines.append('.macro gst_offsets row')
    lines.append('\t.word game_str_ja_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_en_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_de_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_fr_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_it_\\row\\() - game_str_ja')
    lines.append('\t.word game_str_es_\\row\\() - game_str_ja')
    lines.append('.endm')
    lines.append('')
    lines.append('@ ----------------------------------------------------------------------')
    lines.append('game_str_pointer_table:')
    lines.append('@ === Rows 0..1641: 共享 6 lang ===')
    for r in range(N_SHARED_ROWS):
        lines.append(f'\tgst_offsets {r:04d}')

    lines.append('')
    lines.append('@ === Rows 1642..1650: JA-only extras (5 lang col phantom 占位) ===')
    lines.append('@ 5 lang 的 phantom 值从 ROM 硬编码, 落在各 lang region 末尾后, 仅作字节占位')
    for k in range(N_EXTRA_ROWS):
        row_off = TABLE_START + (N_SHARED_ROWS + k) * 24
        vals = struct.unpack_from('<6I', rom, row_off)
        ja_off, en_off, de_off, fr_off, it_off, es_off = vals
        lines.append(f'\t@ Row {N_SHARED_ROWS + k} = JA_EXTRA_{k:02d}')
        lines.append(f'\t.word game_str_ja_extra_{k:02d} - game_str_ja')
        lines.append(f'\t.word 0x{en_off:08X}\t@ EN phantom')
        lines.append(f'\t.word 0x{de_off:08X}\t@ DE phantom')
        lines.append(f'\t.word 0x{fr_off:08X}\t@ FR phantom')
        lines.append(f'\t.word 0x{it_off:08X}\t@ IT phantom')
        lines.append(f'\t.word 0x{es_off:08X}\t@ ES phantom')

    lines.append('')
    lines.append(f'@ 表末 alignment pad ({TRAILING_PAD} bytes)')
    lines.append(f'\t.zero {TRAILING_PAD}')

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    total_bytes = N_TOTAL_ROWS * 24 + TRAILING_PAD
    print(f'wrote {OUT_PATH}')
    print(f'  {N_TOTAL_ROWS} rows x 24 B + {TRAILING_PAD} B pad = {total_bytes} B')
    print(f'  ROM range: 0x{TABLE_START:05X} ~ 0x{end_addr:05X}')


if __name__ == '__main__':
    main()
else:
    main()
