"""
Encoder: text/card-names/{ja,en,de,fr,it,es}.txt + pointer-table.txt → data/card-names.s

编码规则:
  ja: char → codetable idx → 2 byte; 末尾 \0\0
  en/de/fr/it/es: CP1252 单字节; 末尾 \0 + (\0 若总长奇)

输出 .s 结构:
  card_names_table:
    card_name_NNNN: @ comment
    card_name_NNNN_ja: .ascii "..."
    ... (6 lang)
  card_name_pointer_table:
    name_offsets MMMM    @ comment
    ... (2098 行)
"""
import re
import json
from pathlib import Path

SRC_DIR = Path('text/card-names')
OUT_PATH = Path('data/card-names.s')

CT = {int(k): v for k, v in json.loads(
    open('tools/jp-decode/codetable.json', encoding='utf-8').read()
)['by_idx'].items()}

# card-names JA 不含 @4/@5/@7 控制序列 (card-desc 才有), 但保险起见保留同集合
CONTROL_ASCII = {'@', '4', '5', '7'}

char_to_idx = json.loads(
    open('tools/card-names/char_to_idx.json', encoding='utf-8').read()
)


def encode_ja(text):
    out = bytearray()
    for ch in text:
        idx = char_to_idx.get(ch)
        if idx is not None:
            hi = ((idx >> 7) & 0xF) | 0xF0
            lo = (idx & 0x7F) | 0x80
            out.append(hi)
            out.append(lo)
        else:
            cp = ord(ch)
            if cp > 0xFF:
                raise ValueError(f'char {ch!r} (U+{cp:04X}) not in codetable, not ASCII')
            out.append(cp)
    out.extend(b'\x00\x00')
    return bytes(out)


def encode_lang(text):
    payload = text.encode('cp1252')
    out = bytearray(payload)
    out.append(0)
    if len(out) % 2 != 0:
        out.append(0)
    return bytes(out)


def to_octal_ascii(bs):
    parts = []
    for b in bs:
        if b == 0x22: parts.append(r'\"')
        elif b == 0x5C: parts.append(r'\\')
        elif 0x20 <= b < 0x7F: parts.append(chr(b))
        else: parts.append(f'\\{b:03o}')
    return ''.join(parts)


def parse_txt(path):
    content = open(path, encoding='utf-8').read()
    entries = {}
    pat = re.compile(r'^=(\d{4})=\s*\n', re.MULTILINE)
    matches = list(pat.finditer(content))
    for i, m in enumerate(matches):
        cid = int(m.group(1))
        body_start = m.end()
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        body = content[body_start:body_end].rstrip('\n')
        entries[cid] = body
    return entries


# Parse 6 lang
LANGS = ['ja', 'en', 'de', 'fr', 'it', 'es']
all_entries = {}
for lang in LANGS:
    txt_path = SRC_DIR / f'{lang}.txt'
    entries = parse_txt(txt_path)
    print(f'{lang}.txt: {len(entries)} entries')
    for cid, text in entries.items():
        all_entries.setdefault(cid, {})[lang] = text

cids = sorted(all_entries.keys())
print(f'Total master cids: {len(cids)}')

for cid in cids:
    missing = [l for l in LANGS if l not in all_entries[cid]]
    if missing:
        raise SystemExit(f'cid={cid} missing langs: {missing}')

# Encode
print('Encoding...')
enc = {}
for cid in cids:
    for lang in LANGS:
        text = all_entries[cid][lang]
        if lang == 'ja':
            enc[(cid, lang)] = encode_ja(text)
        else:
            enc[(cid, lang)] = encode_lang(text)
total_bytes = sum(len(b) for b in enc.values())
print(f'Encoded {len(enc)} labels, total {total_bytes:,} B')

# Parse pointer-table.txt
pt_pat = re.compile(r'^(\d{4})\s+(\d{4})\s+(.*)$')
pt_entries = []
with open(SRC_DIR / 'pointer-table.txt', encoding='utf-8') as ptf:
    for line in ptf:
        line = line.rstrip('\n')
        if not line or line.startswith('@'):
            continue
        m = pt_pat.match(line)
        if not m:
            continue
        pt_entries.append((int(m.group(1)), int(m.group(2)), m.group(3)))
print(f'Pointer table: {len(pt_entries)} entries')
assert len(pt_entries) == 2098

# Master comment 用 EN 名字
master_comment = {cid: all_entries[cid]['en'].strip() or '(placeholder)' for cid in cids}

# 输出 .s
with open(OUT_PATH, 'w', encoding='utf-8', newline='\n') as f:
    f.write('@ =============================================================================\n')
    f.write('@ Card Names (merged: name pool + pointer table)\n')
    f.write('@ ROM 0x15BB594 - 0x15FFF0C  (280,952 B)\n')
    f.write('@\n')
    f.write('@  1. card_names_table         0x15BB594 - 0x15F3A5C  (230,600 B)\n')
    f.write('@     2054 master entries x 6 langs (JA/EN/DE/FR/IT/ES), null-terminated, 2B-aligned\n')
    f.write('@     alt-art cards share master label\n')
    f.write('@  2. card_name_pointer_table  0x15F3A5C - 0x15FFF0C  (50,352 B = 2098x6 u32)\n')
    f.write('@     name_addr = card_names_table + ptr[card_id*6 + lang_id]\n')
    f.write('@     lang_id: 0=JA 1=EN 2=DE 3=FR 4=IT 5=ES\n')
    f.write('@\n')
    f.write('@ Generated by tools/card-names/encode_txt_to_s.py from text/card-names/*.txt\n')
    f.write('@ DO NOT EDIT directly — edit the .txt sources and re-run encoder.\n')
    f.write('@ =============================================================================\n\n')

    f.write('@ Macro: 6 lang offsets for cid (label - card_names_table)\n')
    f.write('.macro name_offsets cid\n')
    for lang in LANGS:
        f.write(f'\t.word card_name_\\cid\\()_{lang} - card_names_table\n')
    f.write('.endm\n\n')

    f.write('@ -----------------------------------------------------------------------------\n')
    f.write('@ 1. Name Pool (2054 masters x 6 langs, null-terminated, 2B-aligned)\n')
    f.write('@    ROM 0x15BB594 - 0x15F3A5C  (230,600 B)\n')
    f.write('@ -----------------------------------------------------------------------------\n')
    f.write('card_names_table:\n\n')

    for cid in cids:
        f.write(f'card_name_{cid:04d}:  @ {master_comment[cid]}\n')
        for lang in LANGS:
            bs = enc[(cid, lang)]
            f.write(f'card_name_{cid:04d}_{lang}:\n')
            f.write(f'\t.ascii "{to_octal_ascii(bs)}"\n')
        f.write('\n')

    # 池末尾 4-byte 对齐 (与原文一致, 原 .s 通过 cid=2097 es 末尾 4 trailing \0 实现)
    f.write('\t.balign 4\n\n')

    f.write('@ -----------------------------------------------------------------------------\n')
    f.write('@ 2. Pointer Table (2098 cards x 6 langs x u32)\n')
    f.write('@    ROM 0x15F3A5C - 0x15FFF0C  (50,352 B)\n')
    f.write('@ -----------------------------------------------------------------------------\n')
    f.write('card_name_pointer_table:\n\n')
    for cid, master_cid, comment in pt_entries:
        f.write(f'\tname_offsets {master_cid:04d}    @ {comment}\n')

print(f'\nwrote {OUT_PATH}')
