@ data/game-strings.s
@ Game text string table (multi-language)
@ ROM offset: 0x1DC4620 ~ 0x1DFF9D1
@
@ Contains all game strings for 5 languages (EN/DE/FR/IT/ES).
@ Per-language files are generated by: python tools/export_game_strings.py
@
@ File encoding: Latin-1 (ISO 8859-1)
@ Labels deck_str_{lang}_{sd|opp}_NN mark positions pointed to by the pointer table

.include "data/game-strings-en.s"
.include "data/game-strings-de.s"
.include "data/game-strings-fr.s"
.include "data/game-strings-it.s"
.include "data/game-strings-es.s"
