"""export_boot_ui_gfx.py — 提取 0x0800DE30~0x08013510 的 UI 图形 (灰度, 无静态消费者)

该区在语言选择图形 (lang-select, ~0xDE30) 之后、第一个代码函数 reset_display_and_gl_state
(0x13510) 之前, 是若干早期 UI 画面 (菜单/选择: 窗口框/选择框/★/渐变条/网格) 的图形数据。
**无任何静态代码引用** (经 Ghidra 权威引用 + 码区字面量双重确认, 间接/计算寻址加载),
调色板未知 -> 用 16 级灰度预览 (index0 视作透明)。需 mGBA 动态追踪才能确定加载画面+调色板。

内容为交错的 tile (4bpp) / tilemap (4B entry) 段:
  0xDE30..0x10130 tile   0x10130..0x10530 map   0x10530..0x10E30 tile
  0x10E30..0x11530 map   0x11530..0x13510 tile
段边界由内容粗分类 (0x100 粒度), 近似; byte-identical 由顺序 incbin 保证 (与精度无关)。

产出 (仿 graphics/bin/duel-field; 均 gitignore 生成产物):
  graphics/bin/boot-ui/tiles/seg_<addr>.bin       tile 段原始字节
  graphics/bin/boot-ui/tilemaps/seg_<addr>.bin    tilemap 段原始字节
  graphics/images/boot-ui/*.png                    灰度预览 (tile sheet / map 屏幕)
  data/boot-ui-gfx.s                               顺序 .incbin (asm 经 SKIP_REGION .include)
"""
import struct
from pathlib import Path

ROM = Path('roms/2343.gba')
BASE = Path('graphics/bin/boot-ui')
TILE_DIR = BASE / 'tiles'
MAP_DIR = BASE / 'tilemaps'
IMG_DIR = Path('graphics/images/boot-ui')
ASM_OUT = Path('data/boot-ui-gfx.s')

REGION_START = 0xDE30
REGION_END = 0x13510
# (start, end, kind)  kind: 'tile' | 'map'  —— 内容粗分类边界 (近似)
SEGMENTS = [
    (0xDE30, 0x10130, 'tile'),
    (0x10130, 0x10530, 'map'),
    (0x10530, 0x10E30, 'tile'),
    (0x10E30, 0x11530, 'map'),
    (0x11530, 0x13510, 'tile'),
]
GRAY = [(255, 0, 255)] + [(i * 17, i * 17, i * 17) for i in range(1, 16)]  # index0=透明


def u16(d, o):
    return struct.unpack_from('<H', d, o)[0]


def blit(d, px, toff, idx, tx, ty, hf=0, vf=0):
    base = toff + 32 * idx
    for row in range(8):
        for cp in range(4):
            byte = d[base + row * 4 + cp]
            for sub, c in ((0, byte & 0xf), (1, byte >> 4)):
                col = cp * 2 + sub
                px[tx + ((7 - col) if hf else col), ty + ((7 - row) if vf else row)] = GRAY[c]


def tilesheet(d, lo, hi, cols, path):
    from PIL import Image
    n = (hi - lo) // 32
    rows = (n + cols - 1) // cols
    img = Image.new('RGB', (cols * 8, rows * 8), (0, 80, 0))
    px = img.load()
    for t in range(n):
        blit(d, px, lo, t, (t % cols) * 8, (t // cols) * 8)
    img.resize((img.width * 3, img.height * 3), Image.NEAREST).save(path)


def screen(d, map_lo, map_hi, tile_lo, tile_hi, path):
    from PIL import Image
    ents = []
    for o in range(map_lo, map_hi, 4):
        a = u16(d, o)
        b = u16(d, o + 2)
        ents.append((a & 0x3f, a >> 8, b & 0x3ff, b & 0x400, b & 0x800))
    mx = max(x for x, *_ in ents)
    my = max(e[1] for e in ents)
    img = Image.new('RGB', ((mx + 1) * 8, (my + 1) * 8), (0, 80, 0))
    px = img.load()
    nt = (tile_hi - tile_lo) // 32
    for x, y, t, hf, vf in ents:
        if 0 <= t < nt:
            blit(d, px, tile_lo, t, x * 8, y * 8, hf, vf)
    img.resize((img.width * 3, img.height * 3), Image.NEAREST).save(path)


def main():
    d = ROM.read_bytes()
    for p in (TILE_DIR, MAP_DIR, IMG_DIR, ASM_OUT.parent):
        p.mkdir(parents=True, exist_ok=True)

    asm = [
        '@ data/boot-ui-gfx.s',
        '@ 0x%X~0x%X UI 图形 (灰度预览; 无静态消费者, 调色板未知, 需 mGBA 确定)' % (
            0x08000000 + REGION_START, 0x08000000 + REGION_END),
        '@ Generated by tools/rom-export/export_boot_ui_gfx.py',
        '@ 交错 tile(4bpp)/tilemap(4B entry) 段; 段边界近似, byte-identical 由顺序 incbin 保证',
        '',
    ]
    prev_tile = None  # 最近的 tile 段 (供 map 段渲染当 tile bank)
    for (lo, hi, kind) in SEGMENTS:
        addr = 0x08000000 + lo
        raw = d[lo:hi]
        if kind == 'tile':
            (TILE_DIR / ('seg_%08x.bin' % addr)).write_bytes(raw)
            tilesheet(d, lo, hi, 32, IMG_DIR / ('tiles_%08x.png' % addr))
            asm.append('boot_ui_tiles_%08x:            @ 0x%08x  %d tiles (4bpp)' % (addr, addr, (hi - lo) // 32))
            asm.append('\t.incbin "graphics/bin/boot-ui/tiles/seg_%08x.bin"' % addr)
            prev_tile = (lo, hi)
        else:
            (MAP_DIR / ('seg_%08x.bin' % addr)).write_bytes(raw)
            if prev_tile:
                screen(d, lo, hi, prev_tile[0], prev_tile[1], IMG_DIR / ('map_%08x.png' % addr))
            asm.append('boot_ui_tilemap_%08x:          @ 0x%08x  %d entries (4B)' % (addr, addr, (hi - lo) // 4))
            asm.append('\t.incbin "graphics/bin/boot-ui/tilemaps/seg_%08x.bin"' % addr)
        print('[ok] %-4s 0x%08x..0x%08x (0x%x B)' % (kind, addr, 0x08000000 + hi, hi - lo))

    ASM_OUT.write_text('\n'.join(asm) + '\n', encoding='utf-8', newline='\n')
    print('[ok] %s + bins + pngs' % ASM_OUT)


if __name__ == '__main__':
    main()
