#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
内嵌文件系统索引表导出脚本

从 roms/2343.gba 导出 ROM 0x1E63BE8 ~ 0x1E64684 区域：
    - offset_table (339 × u32)  : 累积起点偏移
    - size_table   (340 × u32)  : 每文件压缩后大小（第 0 项 = 总大小）

索引语义（反向工程结论）：
    path[i]  ↔  offset_table[i+1]  ↔  size_table[i+1]
    i.e. 文件 i 从 file_system_base + offset_table[i+1] 开始
              占 size_table[i+1] 字节（offset_table[0] 是占位 sentinel）

FS 数据起点：0x1E64684（紧跟 size_table 末尾）

输出文件：
  data/fs-tables.s   入库
"""

import os
import struct

ROM_PATH = "roms/2343.gba"
OUT = "data/fs-tables.s"

OFFSET_TABLE_START = 0x1E63BE8
OFFSET_TABLE_COUNT = 339
SIZE_TABLE_START = 0x1E64134
SIZE_TABLE_COUNT = 340
FS_BASE = 0x1E64684

# path_table 布局（已有 data/file-paths.s）
PATH_TABLE_START = 0x1E6118C
PATH_STRIDE = 32
PATH_COUNT = 339


def load_paths(rom: bytes) -> list[str]:
    paths = []
    for fid in range(PATH_COUNT):
        raw = rom[PATH_TABLE_START + fid * PATH_STRIDE:
                  PATH_TABLE_START + (fid + 1) * PATH_STRIDE]
        paths.append(raw.split(b"\x00", 1)[0].decode("ascii", errors="replace"))
    return paths


def main():
    with open(ROM_PATH, "rb") as f:
        rom = f.read()

    offsets = struct.unpack_from(f"<{OFFSET_TABLE_COUNT}I", rom, OFFSET_TABLE_START)
    sizes = struct.unpack_from(f"<{SIZE_TABLE_COUNT}I", rom, SIZE_TABLE_START)
    paths = load_paths(rom)

    total_bytes = (OFFSET_TABLE_COUNT + SIZE_TABLE_COUNT) * 4
    assert SIZE_TABLE_START + SIZE_TABLE_COUNT * 4 == FS_BASE, \
        f"size_table 尾部不对齐 FS_BASE"

    lines = []
    lines.append("@ " + "=" * 77)
    lines.append("@ 内嵌文件系统索引表（Filesystem Tables）")
    lines.append(f"@ ROM range: 0x{OFFSET_TABLE_START:07X} - 0x{FS_BASE:07X}"
                 f" (0x{total_bytes:X} = {total_bytes:,} bytes)")
    lines.append("@")
    lines.append("@ 两张平行表 + 紧邻的 FS 数据区：")
    lines.append(f"@   offset_table @ 0x{OFFSET_TABLE_START:07X}: {OFFSET_TABLE_COUNT} × u32，累积起点偏移")
    lines.append(f"@   size_table   @ 0x{SIZE_TABLE_START:07X}: {SIZE_TABLE_COUNT} × u32，压缩后字节数")
    lines.append(f"@   file_system  @ 0x{FS_BASE:07X}: 文件数据起点（本文件不含）")
    lines.append("@")
    lines.append("@ 索引语义：")
    lines.append("@   path[i]  ↔  offset_table[i+1]  ↔  size_table[i+1]")
    lines.append("@   offset_table[0] = 0 是占位 sentinel")
    lines.append("@   size_table[0]   = 0x70350 = 文件系统总字节数")
    lines.append("@")
    lines.append("@ Generated by tools/rom-export/export_fs_tables.py")
    lines.append("@ " + "=" * 77)
    lines.append("")

    # offset_table
    lines.append("@ ------ Cumulative offset table (339 × u32) ------")
    lines.append(f"@ ROM: 0x{OFFSET_TABLE_START:07X} - 0x{SIZE_TABLE_START:07X}"
                 f" ({OFFSET_TABLE_COUNT * 4} bytes)")
    lines.append("fs_offset_table:")
    for i, v in enumerate(offsets):
        if i == 0:
            note = "sentinel (file 0 shares offset with file 1)"
        else:
            path = paths[i - 1] if i - 1 < len(paths) else "?"
            note = f"path[{i - 1}] = {path}"
        lines.append(f"\t.word 0x{v:08X}    @ [{i:>3}] {note}")
    lines.append("")

    # size_table
    lines.append("@ ------ Size table (340 × u32, compressed sizes) ------")
    lines.append(f"@ ROM: 0x{SIZE_TABLE_START:07X} - 0x{FS_BASE:07X}"
                 f" ({SIZE_TABLE_COUNT * 4} bytes)")
    lines.append("fs_size_table:")
    for i, v in enumerate(sizes):
        if i == 0:
            note = "TOTAL filesystem size"
        else:
            path = paths[i - 1] if i - 1 < len(paths) else "?"
            note = f"path[{i - 1}] = {path}"
        lines.append(f"\t.word 0x{v:08X}    @ [{i:>3}] {note}")
    lines.append("")

    out = "\n".join(lines)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)

    print(f"offset_table: {OFFSET_TABLE_COUNT} × u32 = {OFFSET_TABLE_COUNT * 4} B")
    print(f"size_table:   {SIZE_TABLE_COUNT} × u32 = {SIZE_TABLE_COUNT * 4} B")
    print(f"总计:         {total_bytes} B")
    print(f"已写入:       {OUT}")


if __name__ == "__main__":
    main()
