#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
卡牌描述文本导出脚本

从 roms/2343.gba 导出 ROM 0x01800000 ~ 0x018169B6 区域:

  A. 卡牌描述文本 (0x1800000 ~ 0x180A50A)
     39 张卡的效果描述，每卡 6 个 null 终止字符串 (EN/DE/FR/IT/ES/XX)
     格式与 card-names.s 完全一致: CP1252 编码, 2 字节对齐
     XX 语言使用自定义字节编码 (0xF0-0xFF 范围)

  B. u32 数据表 (0x180A50C ~ 0x1816580)
     12,317 个 u32 值, 含义未完全确认

  C. 指针表 (0x1816580 ~ 0x18169B6)
     269 条 u32 文件偏移 + 2 字节尾部

输出文件:
  data/card-descriptions.s    描述文本 + 数据表 + 指针表 (入库)
"""

import os
import struct
import sys

ROM_PATH = 'roms/2343.gba'
OUT_DIR = 'data'
ASM_OUT = os.path.join(OUT_DIR, 'card-descriptions.s')

# ROM 布局
DESCS_START = 0x01800000
PTR_TABLE_START = 0x01816580
AREA_END = 0x018169B6  # card-stats 起始
LANGS_PER_CARD = 6
LANG_NAMES = ['EN', 'DE', 'FR', 'IT', 'ES', 'XX']
PTR_COUNT = 269


def asm_escape(raw: bytes) -> str:
    """将字节序列转换为 GAS .ascii 字面量内容 (CP1252 源文件)。"""
    parts = []
    for b in raw:
        if   b == 0x22: parts.append('\\"')
        elif b == 0x5C: parts.append('\\\\')
        elif b == 0x0A: parts.append('\\n')
        elif b == 0x0D: parts.append('\\r')
        elif b == 0x09: parts.append('\\t')
        elif b == 0x00: parts.append('\\0')
        elif 0x20 <= b < 0x7F:  parts.append(chr(b))
        elif 0x80 <= b <= 0x9F:
            try:    parts.append(bytes([b]).decode('cp1252'))
            except (UnicodeDecodeError, ValueError):
                    parts.append(f'\\x{b:02x}')
        elif 0xA0 <= b <= 0xFF: parts.append(chr(b))
        else:                   parts.append(f'\\x{b:02x}')
    return ''.join(parts)


def read_null_str(rom: bytes, pos: int, limit: int) -> tuple[bytes, int]:
    """读取 null 终止字符串, 返回 (字节串, 下一位置, 2 字节对齐)。"""
    j = pos
    while j < limit and rom[j] != 0:
        j += 1
    s = rom[pos:j]
    end = j + 1
    if end % 2 == 1:
        end += 1
    return s, end


def scan_text_cards(rom: bytes) -> tuple[list, int]:
    """扫描文本描述, 返回 (cards, text_end_offset)。
    cards = [(card_rom_off, [lang0_bytes, ...]), ...]
    """
    p = DESCS_START
    limit = AREA_END
    cards = []

    while p < limit:
        card_start = p
        strs = []
        ok = True
        for _ in range(LANGS_PER_CARD):
            s, p = read_null_str(rom, p, limit)
            strs.append(s)
            if p > limit:
                ok = False
                break
        if not ok:
            p = card_start
            break
        en_str = strs[0]
        # EN 短于 10 字符或含控制字符 → 不是描述文本
        if len(en_str) < 10 or any(
            b < 0x20 and b not in (0x0A, 0x0D, 0x09) for b in en_str
        ):
            p = card_start
            break
        cards.append((card_start, strs))

    return cards, p


def generate_asm(rom: bytes, cards: list, text_end: int) -> str:
    """生成 data/card-descriptions.s。"""
    total_size = AREA_END - DESCS_START
    text_size = text_end - DESCS_START
    bin_data_start = text_end
    # Scan forward past any null padding to find u32 data start
    u32_start = text_end
    while u32_start < PTR_TABLE_START and rom[u32_start] == 0:
        u32_start += 1
    # Align back to 4-byte boundary for u32 reads
    if u32_start % 4 != 0:
        u32_start = u32_start & ~3
    bin_data_size = PTR_TABLE_START - bin_data_start
    ptr_table_size = AREA_END - PTR_TABLE_START

    lines = []
    lines.append('@ =============================================================================')
    lines.append('@ Card Description Text + Data Table + Pointer Table')
    lines.append(f'@ ROM range: 0x{DESCS_START:07X} - 0x{AREA_END:07X}'
                 f' (0x{total_size:X} = {total_size:,} bytes)')
    lines.append('@')
    lines.append(f'@ Section A: Description text - {len(cards)} cards x 6 langs'
                 f' ({text_size:,} bytes)')
    lines.append(f'@ Section B: u32 data table ({bin_data_size:,} bytes)')
    lines.append(f'@ Section C: Pointer table - {PTR_COUNT} entries'
                 f' ({ptr_table_size:,} bytes)')
    lines.append('@')
    lines.append('@ File encoding: CP1252 (Windows-1252)')
    lines.append('@ Generated by tools/rom-export/export_card_descriptions.py')
    lines.append('@ =============================================================================')
    lines.append('')

    # --- Section A: description text ---
    lines.append('@ -----------------------------------------------------------------------------')
    lines.append(f'@ Section A: Description text ({len(cards)} cards x 6 langs)')
    lines.append(f'@ GBA addr: 0x{0x08000000 + DESCS_START:08X}'
                 f'  ROM offset: 0x{DESCS_START:07X}')
    lines.append('@ Format: null-terminated, 2-byte aligned, EN/DE/FR/IT/ES/XX')
    lines.append('@ -----------------------------------------------------------------------------')
    lines.append('')
    lines.append('card_desc_table:')

    for i, (card_off, strs) in enumerate(cards):
        en_preview = strs[0][:60].decode('cp1252', errors='replace')
        lines.append(f'')
        lines.append(f'card_desc_{i:03d}:  @ {en_preview}...')
        for lang_idx, s in enumerate(strs):
            lang = LANG_NAMES[lang_idx]
            null_count = 1
            if (len(s) + 1) % 2 == 1:
                null_count = 2
            content = asm_escape(s) + '\\0' * null_count
            lines.append(f'\t.ascii "{content}"  @ {lang}')

    # --- Padding between text and u32 data ---
    pad_size = u32_start - text_end
    if pad_size > 0:
        lines.append('')
        lines.append(f'\t.zero {pad_size}')

    # --- Section B: u32 data table ---
    lines.append('')
    lines.append('@ -----------------------------------------------------------------------------')
    u32_count = (PTR_TABLE_START - u32_start) // 4
    lines.append(f'@ Section B: u32 data table ({u32_count} entries)')
    lines.append(f'@ GBA addr: 0x{0x08000000 + u32_start:08X}'
                 f'  ROM offset: 0x{u32_start:07X}')
    lines.append('@ -----------------------------------------------------------------------------')
    lines.append('card_desc_data:')

    # Output u32 values, 8 per line
    for row_start in range(0, u32_count, 8):
        row_end = min(row_start + 8, u32_count)
        vals = []
        for j in range(row_start, row_end):
            v = struct.unpack_from('<I', rom, u32_start + j * 4)[0]
            vals.append(f'0x{v:08X}')
        lines.append(f'\t.word  {", ".join(vals)}')

    # Handle any trailing bytes (not u32 aligned)
    trailing = (PTR_TABLE_START - u32_start) % 4
    if trailing > 0:
        trail_off = PTR_TABLE_START - trailing
        trail_bytes = ', '.join(f'0x{rom[trail_off+k]:02X}' for k in range(trailing))
        lines.append(f'\t.byte  {trail_bytes}')

    # --- Section C: pointer table ---
    lines.append('')
    lines.append('@ -----------------------------------------------------------------------------')
    lines.append(f'@ Section C: Pointer table ({PTR_COUNT} u32 file offsets)')
    lines.append(f'@ GBA addr: 0x{0x08000000 + PTR_TABLE_START:08X}'
                 f'  ROM offset: 0x{PTR_TABLE_START:07X}')
    lines.append('@ Points to ROM 0x001FD568 ~ 0x0020A464 (purpose TBD)')
    lines.append('@ -----------------------------------------------------------------------------')
    lines.append('card_desc_ptr_table:')

    for row_start in range(0, PTR_COUNT, 8):
        row_end = min(row_start + 8, PTR_COUNT)
        vals = []
        for j in range(row_start, row_end):
            v = struct.unpack_from('<I', rom, PTR_TABLE_START + j * 4)[0]
            vals.append(f'0x{v:08X}')
        lines.append(f'\t.word  {", ".join(vals)}')

    # Trailing bytes after pointer table
    ptr_data_end = PTR_TABLE_START + PTR_COUNT * 4
    if ptr_data_end < AREA_END:
        trail_size = AREA_END - ptr_data_end
        trail_bytes = ', '.join(
            f'0x{rom[ptr_data_end+k]:02X}' for k in range(trail_size)
        )
        lines.append(f'\t.byte  {trail_bytes}  @ trailing')

    lines.append('')
    return '\n'.join(lines) + '\n'


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))
    os.chdir(project_root)

    if not os.path.exists(ROM_PATH):
        print(f'ERROR: {ROM_PATH} not found', file=sys.stderr)
        sys.exit(1)

    rom = open(ROM_PATH, 'rb').read()

    cards, text_end = scan_text_cards(rom)
    print(f'描述文本: {len(cards)} 张卡, 结束于 0x{text_end:07X}')

    asm_content = generate_asm(rom, cards, text_end)
    with open(ASM_OUT, 'w', encoding='cp1252') as f:
        f.write(asm_content)
    print(f'汇编文件: {ASM_OUT}')
    print('完成。')


if __name__ == '__main__':
    main()
