"""export_ui_tile_blocks.py — 提取语言选择画面的 tile+palette+map 图形块

ROM 0x0800AA10 ~ 0x0800DD90 (4 个块) 是语言选择画面 (render_lang_select_tiles_and_text
@0x080ebbxx 引用) 的图形资源, 经 load_pack_tile_and_map_to_vram 载入 VRAM。

每块 = 三个同构子块, 各 [u16 count][6B 头][count x elem]:
  - palette 子块: elem=2  (u16 BGR555 色)            -> PALRAM
  - tile    子块: elem=32 (8x8 4bpp tile)             -> BG VRAM 0x06004000
  - map     子块: elem=4  (2 x u16: A=(Y<<8)|X, B=tile_idx) -> BG tilemap

产出 (仿 graphics/bin/duel-field 组织; 均 gitignore 生成产物):
  graphics/bin/lang-select/palettes/block_N.bin    纯调色板数据 (n_pal x u16)
  graphics/bin/lang-select/tiles/block_N.bin       纯 tile 数据 (n_tile x 32B)
  graphics/bin/lang-select/tilemaps/block_N.bin    纯 tilemap 数据 (n_map x 4B); 无 map 则不生成
  graphics/images/lang-select/block_N.png          每 tilemap 一张还原图 (无 map 则 tile sheet)
  data/lang-select-tiles.s                          各子块 8B header(.hword) + .incbin 纯数据

byte-identical: data/lang-select-tiles.s 顺序 = [pal hdr][pal data][tile hdr][tile data]
[map hdr][map data] x4 块 = 原 ROM 0xAA10..0xDD90 字节。ExportRangeToGas SKIP_REGIONS 改 .include。
"""
import struct
from pathlib import Path

ROM = Path('roms/2343.gba')
BASE = Path('graphics/bin/lang-select')
PAL_DIR = BASE / 'palettes'
TILE_DIR = BASE / 'tiles'
MAP_DIR = BASE / 'tilemaps'
IMG_DIR = Path('graphics/images/lang-select')
ASM_OUT = Path('data/lang-select-tiles.s')

REGION_START = 0xAA10
REGION_END = 0xDD90


def u16(d, o):
    return struct.unpack_from('<H', d, o)[0]


def parse_block(d, off):
    n_pal = u16(d, off)
    pal_off = off + 8
    a = pal_off + 2 * n_pal
    n_tile = u16(d, a)
    tile_off = a + 8
    b = tile_off + 32 * n_tile
    n_map = u16(d, b)
    map_off = b + 8
    end = map_off + 4 * n_map
    return {
        'start': off, 'end': end,
        'n_pal': n_pal, 'pal_off': pal_off, 'pal_hdr': off,
        'n_tile': n_tile, 'tile_off': tile_off, 'tile_hdr': a,
        'n_map': n_map, 'map_off': map_off, 'map_hdr': b,
    }


def bgr555_to_rgb(c):
    r = (c & 0x1f) << 3
    g = ((c >> 5) & 0x1f) << 3
    b = ((c >> 10) & 0x1f) << 3
    return (r | r >> 5, g | g >> 5, b | b >> 5)


def palette(d, blk):
    pal = [bgr555_to_rgb(u16(d, blk['pal_off'] + 2 * i)) for i in range(blk['n_pal'])]
    while len(pal) < 16:
        pal.append((255, 0, 255))
    return pal


def blit_tile(px, d, tile_off, idx, pal, tx, ty, hflip=False, vflip=False):
    base = tile_off + 32 * idx
    for row in range(8):
        for cp in range(4):
            byte = d[base + row * 4 + cp]
            for sub, c in ((0, byte & 0xf), (1, byte >> 4)):
                col = cp * 2 + sub
                dx = (7 - col) if hflip else col
                dy = (7 - row) if vflip else row
                px[tx + dx, ty + dy] = pal[c]


def render_screen(d, blk, png):
    """按 map 还原真实 BG 排布: entry (A,B) -> tile B 放到 (X=A&0x3f, Y=A>>8)。"""
    from PIL import Image
    pal = palette(d, blk)
    ents = []
    for i in range(blk['n_map']):
        a = u16(d, blk['map_off'] + 4 * i)
        b = u16(d, blk['map_off'] + 4 * i + 2)
        # GBA BG tilemap entry: bits[9:0]=tile, bit10=hflip, bit11=vflip
        ents.append((a & 0x3f, a >> 8, b & 0x3ff, bool(b & 0x400), bool(b & 0x800)))
    max_x = max(x for x, y, t, hf, vf in ents)
    max_y = max(y for x, y, t, hf, vf in ents)
    img = Image.new('RGB', ((max_x + 1) * 8, (max_y + 1) * 8), (255, 0, 255))
    px = img.load()
    for x, y, t, hf, vf in ents:
        if t < blk['n_tile']:
            blit_tile(px, d, blk['tile_off'], t, pal, x * 8, y * 8, hf, vf)
    img.resize((img.width * 3, img.height * 3), Image.NEAREST).save(png)


def render_tilesheet(d, blk, png, cols=16):
    from PIL import Image
    pal = palette(d, blk)
    n = blk['n_tile']
    rows = (n + cols - 1) // cols
    img = Image.new('RGB', (cols * 8, rows * 8), (255, 0, 255))
    px = img.load()
    for t in range(n):
        blit_tile(px, d, blk['tile_off'], t, pal, (t % cols) * 8, (t // cols) * 8)
    img.resize((img.width * 4, img.height * 4), Image.NEAREST).save(png)


def hdr_hwords(d, off):
    return ', '.join('0x%04x' % u16(d, off + 2 * i) for i in range(4))


def main():
    d = ROM.read_bytes()
    for p in (PAL_DIR, TILE_DIR, MAP_DIR, IMG_DIR, ASM_OUT.parent):
        p.mkdir(parents=True, exist_ok=True)

    blocks = []
    off = REGION_START
    while off < REGION_END:
        blk = parse_block(d, off)
        blocks.append(blk)
        off = blk['end']
    assert off == REGION_END, 'block walk 未对齐: 0x%x' % off

    asm = [
        '@ data/lang-select-tiles.s',
        '@ 语言选择画面图形块 (ROM 0x%X~0x%X, %d 块 tile+palette+map)' % (
            0x08000000 + REGION_START, 0x08000000 + REGION_END, len(blocks)),
        '@ Generated by tools/rom-export/export_ui_tile_blocks.py',
        '@ 消费者: render_lang_select_tiles_and_text -> load_pack_tile_and_map_to_vram',
        '@ 每块 = palette/tile/map 三子块; 8B header(.hword 含 count) 在 .s, 纯数据在 .bin',
        '',
    ]
    for i, blk in enumerate(blocks):
        addr = 0x08000000 + blk['start']
        name = 'block_%d' % i
        # 纯数据 bin (无 header), 仿 duel-field 组织
        (PAL_DIR / (name + '.bin')).write_bytes(d[blk['pal_off']:blk['pal_off'] + 2 * blk['n_pal']])
        (TILE_DIR / (name + '.bin')).write_bytes(d[blk['tile_off']:blk['tile_off'] + 32 * blk['n_tile']])
        if blk['n_map']:
            (MAP_DIR / (name + '.bin')).write_bytes(d[blk['map_off']:blk['map_off'] + 4 * blk['n_map']])
            render_screen(d, blk, IMG_DIR / (name + '.png'))      # 每 tilemap 一张图
        else:
            render_tilesheet(d, blk, IMG_DIR / (name + '.png'))   # 无 map -> 直接 tile sheet

        asm.append('lang_select_gfx_%d:                @ 0x%08x  pal=%d tile=%d map=%d' % (
            i, addr, blk['n_pal'], blk['n_tile'], blk['n_map']))
        asm.append('\t.hword %s                @ palette 子块 header (count+meta)' % hdr_hwords(d, blk['pal_hdr']))
        asm.append('\t.incbin "graphics/bin/lang-select/palettes/%s.bin"' % name)
        asm.append('\t.hword %s                @ tile 子块 header' % hdr_hwords(d, blk['tile_hdr']))
        asm.append('\t.incbin "graphics/bin/lang-select/tiles/%s.bin"' % name)
        if blk['n_map']:
            asm.append('\t.hword %s                @ map 子块 header' % hdr_hwords(d, blk['map_hdr']))
            asm.append('\t.incbin "graphics/bin/lang-select/tilemaps/%s.bin"' % name)
        print('[ok] block %d @0x%08x pal=%d tile=%d map=%d' % (
            i, addr, blk['n_pal'], blk['n_tile'], blk['n_map']))

    ASM_OUT.write_text('\n'.join(asm) + '\n', encoding='utf-8', newline='\n')
    print('[ok] %s + bins(palettes/tiles/tilemaps) + %d pngs' % (ASM_OUT, len(blocks)))


if __name__ == '__main__':
    main()
