#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
卡牌名称指针表 (Card Name Pointer Table) 导出脚本

ROM 范围: 0x015F3A5C ~ 0x015FFF6C  (50,448 B = 12,612 × u32)
来源: Data Crystal wiki (refs/datacrystal-um2006/rom-map.md) 反汇编
  pointer = [0x15F3A5C + ((card_id * 6 + language_id) << 2)]
  card_name_addr = 0x15BB594 + pointer

12,612 = 2,102 张卡 × 6 语言 (EN/DE/FR/IT/ES/XX)
卡名字符池起始 0x15BB594, 项目当前 data/card-names.s 自 0x15BB5AC 起
(比池起始晚 0x18 = cid=0 占位槽 24 字节, 6 langs × 4 bytes)。

输出:
  data/card-name-pointer-table.s   (入库)
"""

import os
import struct
import sys

ROM_PATH = 'roms/2343.gba'
OUT_DIR = 'data'
ASM_OUT = os.path.join(OUT_DIR, 'card-name-pointer-table.s')

TABLE_START = 0x015F3A5C
TABLE_END   = 0x015FFF6C
NAMES_BASE  = 0x015BB594
LANGS_PER_CARD = 6
LANG_NAMES  = ['EN', 'DE', 'FR', 'IT', 'ES', 'XX']


def generate_asm(rom: bytes) -> str:
    table_size = TABLE_END - TABLE_START
    n_entries  = table_size // 4
    n_cards    = n_entries // LANGS_PER_CARD

    lines = []
    lines.append('@ =============================================================================')
    lines.append('@ Card Name Pointer Table')
    lines.append(f'@ ROM range: 0x{TABLE_START:07X} - 0x{TABLE_END:07X}'
                 f' (0x{table_size:X} = {table_size:,} bytes)')
    lines.append(f'@ Layout: {n_entries} u32 entries = {n_cards} cards x {LANGS_PER_CARD} langs')
    lines.append('@')
    lines.append('@ Lookup formula (per Data Crystal ROM map, function 0x080EE968):')
    lines.append('@   pointer = card_name_pointer_table[card_id * 6 + language_id]')
    lines.append(f'@   name_addr = 0x{NAMES_BASE:08X} + pointer')
    lines.append('@')
    lines.append('@ language_id: 0=EN(or JP) 1=DE 2=FR 3=IT 4=ES 5=XX')
    lines.append('@ Generated by tools/rom-export/export_card_name_pointer_table.py')
    lines.append('@ =============================================================================')
    lines.append('')
    lines.append('    .section .rodata')
    lines.append('    .balign 4')
    lines.append('    .global card_name_pointer_table')
    lines.append('card_name_pointer_table:')
    lines.append('')

    for cid in range(n_cards):
        vals = []
        for lang in range(LANGS_PER_CARD):
            idx = cid * LANGS_PER_CARD + lang
            v = struct.unpack_from('<I', rom, TABLE_START + idx * 4)[0]
            vals.append(f'0x{v:08X}')
        lines.append(f'    .word  {", ".join(vals)}    @ cid={cid:04d}')

    lines.append('')
    return '\n'.join(lines) + '\n'


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))
    os.chdir(project_root)

    if not os.path.exists(ROM_PATH):
        print(f'ERROR: {ROM_PATH} not found', file=sys.stderr)
        sys.exit(1)

    rom = open(ROM_PATH, 'rb').read()

    table_size = TABLE_END - TABLE_START
    n_entries  = table_size // 4
    n_cards    = n_entries // LANGS_PER_CARD
    print(f'指针表: {n_entries} entries = {n_cards} cards x {LANGS_PER_CARD} langs')
    print(f'  范围 0x{TABLE_START:07X}..0x{TABLE_END:07X} ({table_size:,} bytes)')

    asm_content = generate_asm(rom)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(ASM_OUT, 'w', encoding='ascii') as f:
        f.write(asm_content)
    print(f'汇编文件: {ASM_OUT} ({len(asm_content):,} 字符)')
    print('完成。')


if __name__ == '__main__':
    main()
