#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
内部文件路径表导出脚本

从 roms/2343.gba 导出 ROM 0x01E6118C ~ 0x01E63BE8 区域:
339 条 null 终止 ASCII 文件路径（deck/*.ydc, titleEx/*.LZncgr 等）

输出文件:
  data/file-paths.s    文件路径表 (入库)
"""

import os
import sys

ROM_PATH = 'roms/2343.gba'
OUT_DIR = 'data'
ASM_OUT = os.path.join(OUT_DIR, 'file-paths.s')

# ROM 布局
REGION_START = 0x01E6118C
REGION_END   = 0x01E63BE8  # 4-byte aligned end after last null


def scan_paths(rom: bytes) -> list[tuple[int, bytes]]:
    """扫描 null 终止路径字符串，返回 [(rom_offset, raw_bytes), ...]。"""
    paths = []
    pos = REGION_START
    while pos < REGION_END:
        if rom[pos] == 0:
            pos += 1
            continue
        start = pos
        while pos < REGION_END and rom[pos] != 0:
            pos += 1
        raw = rom[start:pos]
        paths.append((start, raw))
        pos += 1  # skip null
    return paths


def generate_asm(rom: bytes, paths: list) -> str:
    """生成 data/file-paths.s。"""
    total_size = REGION_END - REGION_START

    lines = []
    lines.append('@ =============================================================================')
    lines.append('@ Internal File Path Table')
    lines.append(f'@ ROM range: 0x{REGION_START:07X} - 0x{REGION_END:07X}'
                 f' (0x{total_size:X} = {total_size:,} bytes)')
    lines.append(f'@ {len(paths)} null-terminated ASCII file paths')
    lines.append('@')
    lines.append('@ Contains: deck/*.ydc (opponent/structure decks),')
    lines.append('@           titleEx/*.LZncgr/LZnclr/LZnscr (compressed graphics)')
    lines.append('@ Generated by tools/rom-export/export_file_paths.py')
    lines.append('@ =============================================================================')
    lines.append('')
    lines.append('file_path_table:')

    # Output each path, tracking position for padding
    pos = REGION_START
    for i, (offset, raw) in enumerate(paths):
        # Emit any gap bytes (nulls between strings beyond the terminator)
        gap = offset - pos
        if gap > 0:
            # These are padding null bytes
            lines.append(f'\t.zero {gap}')

        path_str = raw.decode('ascii')
        lines.append(f'\t.asciz "{path_str}"')
        pos = offset + len(raw) + 1  # +1 for null terminator

    # Trailing bytes to reach REGION_END
    trail = REGION_END - pos
    if trail > 0:
        lines.append(f'\t.zero {trail}')

    lines.append('')
    return '\n'.join(lines) + '\n'


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))
    os.chdir(project_root)

    if not os.path.exists(ROM_PATH):
        print(f'ERROR: {ROM_PATH} not found', file=sys.stderr)
        sys.exit(1)

    rom = open(ROM_PATH, 'rb').read()

    paths = scan_paths(rom)
    print(f'文件路径: {len(paths)} 条')
    print(f'  首条: {paths[0][1].decode("ascii")}')
    print(f'  末条: {paths[-1][1].decode("ascii")}')

    asm_content = generate_asm(rom, paths)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(ASM_OUT, 'w', encoding='ascii') as f:
        f.write(asm_content)
    print(f'汇编文件: {ASM_OUT}')

    # 验证大小
    # 计算生成的 .s 会产出的字节数
    expected_size = REGION_END - REGION_START
    print(f'预期字节数: {expected_size:,}')
    print('完成。')


if __name__ == '__main__':
    main()
