#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
决斗题目存档模板导出脚本

从 roms/2343.gba 导出 ROM 0x01EB90D8 ~ 0x01EC33D9 区域:
文本格式的决斗题目（DUEL QUESTION）模板数据，INI 风格键值对，CRLF 换行。
部分值包含高字节（0x80+），可能为卡牌名称的自定义编码。

输出文件:
  data/duel-puzzles.s    决斗题目数据 (入库)
"""

import os
import sys

ROM_PATH = 'roms/2343.gba'
OUT_DIR = 'data'
ASM_OUT = os.path.join(OUT_DIR, 'duel-puzzles.s')

# ROM 布局
REGION_START = 0x01EB90D8
REGION_END   = 0x01EC33D9  # 紧接 [END]\r\n 之后


def asm_escape(raw: bytes) -> str:
    """将字节序列转换为 GAS .ascii 字面量内容。"""
    parts = []
    for b in raw:
        if   b == 0x22: parts.append('\\"')
        elif b == 0x5C: parts.append('\\\\')
        elif b == 0x0A: parts.append('\\n')
        elif b == 0x0D: parts.append('\\r')
        elif b == 0x09: parts.append('\\t')
        elif b == 0x00: parts.append('\\0')
        elif 0x20 <= b < 0x7F: parts.append(chr(b))
        else: parts.append(f'\\{b:03o}')
    return ''.join(parts)


def parse_puzzles(rom: bytes) -> list[tuple[int, bytes]]:
    """解析决斗题目块，按 [DUEL QUESTION] 标记分割原始字节。
    返回 [(rom_offset, raw_bytes), ...]。
    """
    data = rom[REGION_START:REGION_END]
    marker = b'[DUEL QUESTION]'

    puzzles = []
    # Find all marker positions in raw bytes
    positions = []
    search_start = 0
    while True:
        idx = data.find(marker, search_start)
        if idx == -1:
            break
        positions.append(idx)
        search_start = idx + len(marker)

    for i, pos in enumerate(positions):
        # Each puzzle extends from this marker to the next (or end)
        end = positions[i + 1] if i + 1 < len(positions) else len(data)
        raw = data[pos:end]
        puzzles.append((REGION_START + pos, raw))

    return puzzles


def generate_asm(rom: bytes, puzzles: list) -> str:
    """生成 data/duel-puzzles.s。"""
    total_size = REGION_END - REGION_START

    lines = []
    lines.append('@ =============================================================================')
    lines.append('@ Duel Puzzle Data (DUEL QUESTION Templates)')
    lines.append(f'@ ROM range: 0x{REGION_START:07X} - 0x{REGION_END:07X}'
                 f' (0x{total_size:X} = {total_size:,} bytes)')
    lines.append(f'@ {len(puzzles)} duel puzzle blocks, INI-style key=value, CRLF line endings')
    lines.append('@')
    lines.append('@ Generated by tools/rom-export/export_duel_puzzles.py')
    lines.append('@ =============================================================================')
    lines.append('')
    lines.append('duel_puzzle_data:')

    for i, (offset, raw) in enumerate(puzzles):
        lines.append('')
        # Extract info for comment (scan ASCII-safe portion)
        phase = ''
        player_lp = ''
        for bline in raw.split(b'\r\n'):
            if bline.startswith(b'Phase='):
                phase = bline[6:].decode('ascii', errors='replace')
            if bline.startswith(b'PlayerLP0='):
                player_lp = bline[10:].decode('ascii', errors='replace')

        info = f'Phase={phase}' if phase else ''
        if player_lp:
            info += f', LP0={player_lp}'
        lines.append(f'duel_puzzle_{i:03d}:  @ {info}')

        # Split by CRLF and output each line as .ascii
        crlf_lines = raw.split(b'\r\n')
        for j, bline in enumerate(crlf_lines):
            content = asm_escape(bline)
            if j < len(crlf_lines) - 1:
                content += '\\r\\n'
            if content:
                lines.append(f'\t.ascii "{content}"')

    lines.append('')
    return '\n'.join(lines) + '\n'


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))
    os.chdir(project_root)

    if not os.path.exists(ROM_PATH):
        print(f'ERROR: {ROM_PATH} not found', file=sys.stderr)
        sys.exit(1)

    rom = open(ROM_PATH, 'rb').read()

    puzzles = parse_puzzles(rom)
    print(f'决斗题目: {len(puzzles)} 块')

    asm_content = generate_asm(rom, puzzles)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(ASM_OUT, 'w', encoding='ascii') as f:
        f.write(asm_content)
    print(f'汇编文件: {ASM_OUT}')
    print(f'预期字节数: {REGION_END - REGION_START:,}')
    print('完成。')


if __name__ == '__main__':
    main()
