#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
卡牌密码表（加密）导出脚本

ROM 0x015B94CC - 0x015BB594 (8,392 B = 2098 × u32)

加密公式（反编译自 FUN_080ef370 @ 0x080EF370，用 FUN_080f5e00 @ 0x080F5E00 生成 key）:
    key(cid)        = ((cid * 0x343FD + 0x269EC3) >> 16) | 0x9EC30000
    passcode_bcd    = table[cid] XOR key(cid)
    密码 = int(hex(passcode_bcd))  # 十六进制数字直接读作十进制

乘数/加数 0x343FD / 0x269EC3 是 Borland C rand() 的 LCG 参数。

验证:
    cid=1 Blue-Eyes → table=0x17A01110, key=0x9EC30029, decrypt=0x89631139 = 89631139 ✓
    全 ROM 2080 张合法密码卡 → 2078 与 data.md 一致
    cid=0 / cid=2081..2097 (17 tokens) 解密出非十进制，属占位/代币无密码

    与 data.md 差异的 2 张均为 "Premium Pack 特殊印刷版本" 选型（不同卡图 → 不同密码）:
      cid=689  Polymerization   ROM=27847700 (Premium Pack 6 版) / data.md=24094653 (通常版)
      cid=911  Dark Magician    ROM=36996508 (Premium Pack 4, 潘多拉版) / data.md=46986414 (通常版)
    游戏内逆查密码以 ROM 值为准。

输出:
    data/card-passcodes.s
"""

import os
import re
import struct
import sys

ROM_PATH   = 'roms/2343.gba'
OUT_DIR    = 'data'
ASM_OUT    = os.path.join(OUT_DIR, 'card-passcodes.s')

TABLE_START = 0x015B94CC
TABLE_END   = 0x015BB594
N_CARDS     = 2098

# EN name 从 card_names pool 提取，与 export_card_data.py 同一来源
NAMES_POOL_START = 0x015BB594
NAME_PTR_START   = 0x015F3A5C


def lcg_key(cid: int) -> int:
    """逐 cid 生成的 XOR key；见 FUN_080f5e00。"""
    v = (cid * 0x343FD + 0x269EC3) & 0xFFFFFFFF
    return ((v >> 16) | 0x9EC30000) & 0xFFFFFFFF


def extract_en_name(rom: bytes, cid: int) -> str:
    """从卡名指针表读 cid 的 EN 字符串（lang_id=1），去尾 null。"""
    en_ptr = struct.unpack_from('<I', rom, NAME_PTR_START + (cid * 6 + 1) * 4)[0]
    addr   = NAMES_POOL_START + en_ptr
    end    = addr
    while end < len(rom) and rom[end] != 0:
        end += 1
    return rom[addr:end].decode('cp1252', errors='replace')


def master_of_cid(rom: bytes) -> list[int]:
    """6-tuple 首次出现判 master_cid（与 card-names.s 一致）。"""
    ptrs = [struct.unpack_from('<I', rom, NAME_PTR_START + i*4)[0]
            for i in range(N_CARDS * 6)]
    seen: dict[tuple, int] = {}
    out = [0] * N_CARDS
    for cid in range(N_CARDS):
        grp = tuple(ptrs[cid*6:(cid+1)*6])
        out[cid] = seen.setdefault(grp, cid)
    return out


def decode_passcode(value: int) -> str | None:
    """若 value 的 8 位十六进制数字全为十进制数字，返回去前导零后的字符串。"""
    s = f'{value:08X}'
    if all(c in '0123456789' for c in s):
        return str(int(s))
    return None


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))
    os.chdir(project_root)

    if not os.path.exists(ROM_PATH):
        print(f'ERROR: {ROM_PATH} not found', file=sys.stderr)
        sys.exit(1)

    rom = open(ROM_PATH, 'rb').read()

    assert TABLE_END - TABLE_START == N_CARDS * 4, \
        f'表大小应为 {N_CARDS}×4, 实际 {TABLE_END - TABLE_START}'

    master_of = master_of_cid(rom)
    en_names  = [extract_en_name(rom, cid) for cid in range(N_CARDS)]

    out: list[str] = []
    out.append('@ =============================================================================')
    out.append('@ Card Passcode Table (encrypted)')
    out.append(f'@ ROM 0x{TABLE_START:07X} - 0x{TABLE_END:07X}'
               f'  ({TABLE_END - TABLE_START:,} B = {N_CARDS} × u32)')
    out.append('@')
    out.append('@ 加密公式 (反编译自 FUN_080ef370 @ 0x080EF370):')
    out.append('@   key(cid)      = ((cid * 0x343FD + 0x269EC3) >> 16) | 0x9EC30000')
    out.append('@   passcode_bcd  = table[cid] XOR key(cid)')
    out.append('@   密码           = int(hex_str(passcode_bcd))  -- 16 进制数字直接读作 10 进制')
    out.append('@')
    out.append('@ 乘数/加数 0x343FD / 0x269EC3 = Borland C rand() 的 LCG 参数')
    out.append('@ 逆查用途: 密码 → cid，由 FUN_080ef38c 线性扫描全表对比。')
    out.append('@')
    out.append('@ cid=0 (placeholder) 与 cid=2081..2097 (17 tokens) 解密非十进制 → 占位/无密码')
    out.append('@ 2078/2080 有效密码与 data.md 一致；余 2 张 ROM 用 Premium Pack 异画版密码：')
    out.append('@   cid=689 Polymerization = 27847700 (Premium Pack 6)')
    out.append('@   cid=911 Dark Magician  = 36996508 (Premium Pack 4 潘多拉版)')
    out.append('@ Generated by tools/rom-export/export_card_passcodes.py')
    out.append('@ =============================================================================')
    out.append('')
    out.append('\t.balign 4')
    out.append('card_passcode_table:')

    for cid in range(N_CARDS):
        enc = struct.unpack_from('<I', rom, TABLE_START + cid * 4)[0]
        dec = enc ^ lcg_key(cid)
        pw  = decode_passcode(dec)

        mc = master_of[cid]
        name = en_names[mc]
        alt  = '' if mc == cid else ' (alt-art)'

        if pw is not None:
            desc = f'{name[:44]}{alt} (pw {pw})'
        elif mc == 0:
            desc = '(placeholder)'
        else:
            desc = f'{name[:44]}{alt} (token, no passcode)'

        out.append(f'\t.word 0x{enc:08X}    '
                   f'@ cid={cid:04d}, {desc}')

    out.append('')

    content = '\n'.join(out) + '\n'
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(ASM_OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)

    valid = sum(1 for cid in range(N_CARDS)
                if decode_passcode(struct.unpack_from('<I', rom, TABLE_START + cid*4)[0]
                                   ^ lcg_key(cid)) is not None)
    print(f'[PASSCODES] {ASM_OUT}')
    print(f'  ROM: 0x{TABLE_START:08X} ~ 0x{TABLE_END-1:08X}  ({TABLE_END - TABLE_START:,} B)')
    print(f'  Entries: {N_CARDS}  (valid-decimal decrypts: {valid}, '
          f'non-decimal: {N_CARDS - valid})')
    print(f'  Output: {len(content):,} chars, {content.count(chr(10)):,} lines')


if __name__ == '__main__':
    main()
