#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
卡牌效果描述全文导出脚本

从 roms/2343.gba 导出 ROM 0x015FFF6C ~ 0x01800000 区域:

  卡牌效果描述文本池
  2014 张卡的效果描述，每卡 6 个 null 终止字符串 (EN/DE/FR/IT/ES/XX)
  格式与 card-names.s 完全一致: CP1252 编码, 2 字节对齐
  XX 语言使用自定义字节编码 (0xF0-0xFF 范围)

注: 原区域起始 0x015F3A5C 处的 u32 数据表 (12,612 entries) 已拆出
    至 data/card-name-pointer-table.s
    (依据 Data Crystal wiki 反汇编，该表是卡名指针表)

输出文件:
  data/card-effect-text.s    描述文本 (入库, CP1252 编码)
"""

import os
import struct
import sys

ROM_PATH = 'roms/2343.gba'
OUT_DIR = 'data'
ASM_OUT = os.path.join(OUT_DIR, 'card-effect-text.s')

# ROM 布局
AREA_START    = 0x015FFF6C
TEXT_START    = 0x015FFF6C
AREA_END      = 0x01800000
LANGS_PER_CARD = 6
LANG_NAMES    = ['EN', 'DE', 'FR', 'IT', 'ES', 'XX']


def asm_escape(raw: bytes) -> str:
    """将字节序列转换为 GAS .ascii 字面量内容 (CP1252 源文件)。"""
    parts = []
    for b in raw:
        if   b == 0x22: parts.append('\\"')
        elif b == 0x5C: parts.append('\\\\')
        elif b == 0x0A: parts.append('\\n')
        elif b == 0x0D: parts.append('\\r')
        elif b == 0x09: parts.append('\\t')
        elif b == 0x00: parts.append('\\0')
        elif 0x20 <= b < 0x7F:  parts.append(chr(b))
        elif 0x80 <= b <= 0x9F:
            try:    parts.append(bytes([b]).decode('cp1252'))
            except (UnicodeDecodeError, ValueError):
                    parts.append(f'\\{b:03o}')
        elif 0xA0 <= b <= 0xFF: parts.append(chr(b))
        else:                   parts.append(f'\\{b:03o}')
    return ''.join(parts)


def read_null_str(rom: bytes, pos: int, limit: int) -> tuple[bytes, int]:
    """读取 null 终止字符串, 返回 (字节串, 下一位置, 2 字节对齐)。"""
    j = pos
    while j < limit and rom[j] != 0:
        j += 1
    s = rom[pos:j]
    end = j + 1
    if end % 2 == 1:
        end += 1
    return s, end


def scan_text_cards(rom: bytes) -> tuple[list, int]:
    """扫描文本描述, 返回 (cards, text_end_offset)。
    cards = [(card_rom_off, [lang0_bytes, ...]), ...]
    """
    p = TEXT_START
    limit = AREA_END
    cards = []

    while p < limit:
        card_start = p
        strs = []
        ok = True
        for _ in range(LANGS_PER_CARD):
            s, p = read_null_str(rom, p, limit)
            strs.append(s)
            if p > limit:
                ok = False
                break
        if not ok:
            p = card_start
            break
        en_str = strs[0]
        # EN 短于 2 字符 → 不是描述文本（最后一块可能较短）
        if len(en_str) < 2 or any(
            b < 0x20 and b not in (0x0A, 0x0D, 0x09) for b in en_str
        ):
            p = card_start
            break
        cards.append((card_start, strs))

    return cards, p


def generate_asm(rom: bytes, cards: list, text_end: int) -> str:
    """生成 data/card-effect-text.s (仅文本池, 不含 u32 表)。"""
    text_size = AREA_END - TEXT_START

    lines = []
    lines.append('@ =============================================================================')
    lines.append('@ Card Effect Text Pool')
    lines.append(f'@ ROM range: 0x{TEXT_START:07X} - 0x{AREA_END:07X}'
                 f' (0x{text_size:X} = {text_size:,} bytes)')
    lines.append(f'@ Layout: {len(cards)} cards x 6 langs (EN/DE/FR/IT/ES/XX)')
    lines.append('@')
    lines.append('@ Format: null-terminated, 2-byte aligned, CP1252 encoding')
    lines.append('@ XX language uses custom byte encoding (0xF0-0xFF range)')
    lines.append('@')
    lines.append('@ Note: leading u32 table (0x15F3A5C..0x15FFF6C, 12612 entries) was')
    lines.append('@       split out to data/card-name-pointer-table.s')
    lines.append('@       (card name pointer table, verified via Data Crystal disasm)')
    lines.append('@')
    lines.append('@ Generated by tools/rom-export/export_card_effect_text.py')
    lines.append('@ =============================================================================')
    lines.append('')
    lines.append('card_effect_text_pool:')

    for i, (card_off, strs) in enumerate(cards):
        en_preview = strs[0][:60].decode('cp1252', errors='replace')
        lines.append(f'')
        lines.append(f'card_effect_{i:04d}:  @ {en_preview}...')
        for lang_idx, s in enumerate(strs):
            lang = LANG_NAMES[lang_idx]
            null_count = 1
            if (len(s) + 1) % 2 == 1:
                null_count = 2
            content = asm_escape(s) + '\\0' * null_count
            lines.append(f'\t.ascii "{content}"  @ {lang}')

    # --- Trailing bytes after last card text ---
    trail_size = AREA_END - text_end
    if trail_size > 0:
        lines.append('')
        lines.append(f'@ Trailing {trail_size} bytes after last card text')
        # Output as raw bytes
        pos = text_end
        while pos < AREA_END:
            chunk_end = min(pos + 16, AREA_END)
            byte_vals = ', '.join(f'0x{rom[pos+k]:02X}' for k in range(chunk_end - pos))
            lines.append(f'\t.byte  {byte_vals}')
            pos = chunk_end

    lines.append('')
    return '\n'.join(lines) + '\n'


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))
    os.chdir(project_root)

    if not os.path.exists(ROM_PATH):
        print(f'ERROR: {ROM_PATH} not found', file=sys.stderr)
        sys.exit(1)

    rom = open(ROM_PATH, 'rb').read()

    cards, text_end = scan_text_cards(rom)
    print(f'效果描述: {len(cards)} 张卡, 文本结束于 0x{text_end:07X}')
    print(f'  首卡: {cards[0][1][0][:50].decode("cp1252", errors="replace")}...')
    print(f'  末卡: {cards[-1][1][0][:50].decode("cp1252", errors="replace")}...')

    asm_content = generate_asm(rom, cards, text_end)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(ASM_OUT, 'w', encoding='cp1252') as f:
        f.write(asm_content)
    print(f'汇编文件: {ASM_OUT} ({len(asm_content):,} 字符)')
    print(f'预期字节数: {AREA_END - TEXT_START:,}')
    print('完成。')


if __name__ == '__main__':
    main()
