# -*- coding: utf-8 -*-
#@runtime Jython
#@category Ygo-ex2006
# FixF01Seg7LiteralPools.py -- f01 Seg-7 literal pool fix
#   After DisassembleF01Seg7Blocks.py runs, the flow-based disassembler
#   may decode literal pool entries as .byte data instead of .word DWORDs.
#   This script forces createDWord on all 167 literal pool targets within
#   blocks 2/3/4, ensuring GAS exporter emits ".word" instead of ".byte".
#
#   Same pattern as FixF01Seg6LiteralPools.py.
#   Generated by scanning asm/01_vija_scene_text.s for DAT_ labels with .byte content.

from ghidra.program.model.data import DWordDataType
from ghidra.program.model.symbol import SourceType

DRY = False
try:
    _a = list(getScriptArgs())
    if _a and _a[0].lower() in ("dry", "--dry", "1", "true"):
        DRY = True
except Exception:
    pass

LITERAL_POOL_TARGETS = [
    # Block2 literal pool (FUN_080211b4/FUN_080211fc shared pool at 0x080211ec..0x080211fb)
    (0x080211ec, 0x08000f40),
    (0x080211f0, 0x02000000),
    (0x080211f4, 0x00006c2c),
    (0x080211f8, 0x09db9c10),
    # Block3 literal pools (51 stubs, language dispatch LP strings + gPrng refs)
    (0x08021550, 0x09df1f72),
    (0x08021558, 0x09de5c7a),
    (0x08021560, 0x09dd98d6),
    (0x080215b8, 0x09df1aea),
    (0x080215c0, 0x09de585e),
    (0x080215c8, 0x09dd9448),
    (0x08021634, 0x09df1b36),
    (0x0802163c, 0x09de58ae),
    (0x08021644, 0x09dd9496),
    (0x08022270, 0x09df1f54),
    (0x08022278, 0x09de5c52),
    (0x08022280, 0x09dd98a4),
    (0x08022338, 0x09df1f54),
    (0x08022340, 0x09de5c52),
    (0x08022348, 0x09dd98a4),
    (0x08022400, 0x09df1f54),
    (0x08022408, 0x09de5c52),
    (0x08022410, 0x09dd98a4),
    (0x0802246c, 0x0201e2a0),
    (0x08022470, 0x02023360),
    (0x08022474, 0x0201c4e0),
    (0x08022478, 0x00001cec),
    (0x080224d0, 0x09df1f92),
    (0x080224d8, 0x09de5ca6),
    (0x080224e0, 0x09dd98f8),
    (0x080224e8, 0x09dcd994),
    (0x08022550, 0x09df1fae),
    (0x08022558, 0x09de5cc6),
    (0x08022560, 0x09dd991e),
    (0x08022568, 0x09dcd9aa),
    (0x080225cc, 0x09df1fd4),
    (0x080225d4, 0x09de5cea),
    (0x080225dc, 0x09dd9956),
    (0x080225f4, 0x09dcd9ce),
    (0x080225f8, 0x02023360),
    (0x080225fc, 0x00001f3f),
    (0x08022640, 0x02000000),
    (0x08022644, 0x00006c2c),
    (0x08022648, 0x09dc2dfa),
    (0x0802264c, 0x0003ae4e),
    (0x08022654, 0x09df1fd4),
    (0x0802265c, 0x09de5cea),
    (0x08022664, 0x09dd9956),
    (0x0802267c, 0x09dcd9ce),
    (0x08022680, 0x02023360),
    (0x08022684, 0x00001f3f),
    (0x0802270c, 0x09df2012),
    (0x08022714, 0x09de5d1e),
    (0x0802271c, 0x09dd99a0),
    (0x0802272c, 0x09dcda00),
    (0x0802278c, 0x09df204c),
    (0x08022794, 0x09de5d5e),
    (0x0802279c, 0x09dd99ec),
    (0x080227a4, 0x09dcda2c),
    (0x08022830, 0x09df1f54),
    (0x08022838, 0x09de5c52),
    (0x08022840, 0x09dd98a4),
    (0x08022868, 0x09dcd960),
    (0x0802286c, 0x000016ec),
    (0x08022870, 0x02023360),
    (0x0802288c, 0x0201e2a0),
    (0x08022890, 0x00001954),
    (0x08022938, 0x0201e2a0),
    (0x0802293c, 0x000019a3),
    (0x08022958, 0x0201e2a0),
    (0x0802295c, 0x000019a4),
    (0x08022978, 0x0201e2a0),
    (0x0802297c, 0x000019a5),
    (0x08022994, 0x0201e2a0),
    (0x08022998, 0x000016cf),
    (0x080229b0, 0x0201e2a0),
    (0x080229b4, 0x000015ef),
    (0x08022a34, 0x09df20f8),
    (0x08022a3c, 0x09de5e3c),
    (0x08022a44, 0x09dd9ab2),
    (0x08022a4c, 0x09dcdad8),
    (0x08022ad8, 0x09df2108),
    (0x08022ae0, 0x09de5e4c),
    (0x08022ae8, 0x09dd9ac4),
    (0x08022b78, 0x09df2130),
    (0x08022b80, 0x09de5e76),
    (0x08022b88, 0x09dd9aec),
    (0x08022bac, 0x09dcdb04),
    (0x08022bb0, 0x02023360),
    (0x08022bcc, 0x0201e2a0),
    (0x08022bd0, 0x00000fe9),
    (0x08022bec, 0x0201e2a0),
    (0x08022bf0, 0x0000111c),
    (0x08022c0c, 0x0201e2a0),
    (0x08022c10, 0x0000138a),
    (0x08022c2c, 0x0201e2a0),
    (0x08022c30, 0x0000146e),
    (0x08022cf0, 0x09df2196),
    (0x08022cf8, 0x09de5efa),
    (0x08022d00, 0x09dd9b5a),
    (0x08022df8, 0x09ded5de),
    (0x08022e00, 0x09de1142),
    (0x08022e08, 0x09dd4eb0),
    # Block4 literal pools (15 stubs, gPrng + language dispatch LP strings)
    (0x08023040, 0x02000000),
    (0x08023044, 0x00006c2c),
    (0x08023048, 0x09dba750),
    (0x0802304c, 0x0003a30c),
    (0x08023054, 0x09de8ab2),
    (0x0802305c, 0x09ddc6cc),
    (0x08023064, 0x09dd037a),
    (0x080230b0, 0x09dec2c6),
    (0x080230b8, 0x09ddffc8),
    (0x080230c0, 0x09dd3cec),
    (0x08023108, 0x09dec2cc),
    (0x08023110, 0x09ddffce),
    (0x08023118, 0x09dd3cf2),
    (0x080231b8, 0x09deeca0),
    (0x080231c0, 0x09de27ec),
    (0x080231c8, 0x09dd6478),
    (0x08023214, 0x09deecb2),
    (0x0802321c, 0x09de2802),
    (0x08023224, 0x09dd648e),
    (0x0802326c, 0x09deecb8),
    (0x08023274, 0x09de280a),
    (0x0802327c, 0x09dd6496),
    (0x080232b8, 0x02000000),
    (0x080232bc, 0x00006c2c),
    (0x080232c0, 0x09dbfda6),
    (0x080232c4, 0x0003ab14),
    (0x080232cc, 0x09deecd8),
    (0x080232d4, 0x09de282c),
    (0x080232dc, 0x09dd64b2),
    (0x08023328, 0x09deecb2),
    (0x08023330, 0x09de2802),
    (0x08023338, 0x09dd648e),
    (0x08023380, 0x09deecb8),
    (0x08023388, 0x09de280a),
    (0x08023390, 0x09dd6496),
    (0x080233a4, 0x09dcab9e),
    (0x080233a8, 0x03000040),
    (0x080233ac, 0x00000202),
    (0x08023404, 0x03000040),
    (0x08023408, 0x00000202),
    (0x0802340c, 0xffffc03f),
    (0x08023580, 0x03000040),
    (0x08023584, 0x00000202),
    (0x08023588, 0xffffc03f),
    (0x080235b4, 0x03000040),
    (0x080235b8, 0x00000202),
    (0x080235bc, 0xffffc03f),
    (0x08023604, 0x03000040),
    (0x08023608, 0x00000203),
    (0x0802360c, 0x00000202),
    (0x08023610, 0xffffc03f),
    (0x08023660, 0x03000040),
    (0x08023664, 0x00000203),
    (0x08023668, 0xffffc03f),
    (0x080236c4, 0x09def19a),
    (0x080236cc, 0x09de2d00),
    (0x080236d4, 0x09dd6982),
    (0x080236e4, 0x09dcafac),
    (0x08023710, 0x02000000),
    (0x08023714, 0x00006c2c),
    (0x08023718, 0x09dc01de),
    (0x0802371c, 0x0003ab86),
    (0x08023724, 0x09def1a6),
    (0x0802372c, 0x09de2d08),
    (0x08023734, 0x09dd698c),
]


def _addr(v):
    return currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(v)


def main():
    print("=== FixF01Seg7LiteralPools (DRY=%s) ===" % DRY)
    listing = currentProgram.getListing()
    dt = DWordDataType()
    nok = nfail = 0

    for addr_int, expected_val in LITERAL_POOL_TARGETS:
        if DRY:
            print("[dry] createDWord @ 0x%08x (0x%08x)" % (addr_int, expected_val))
            nok += 1
            continue

        addr = _addr(addr_int)
        try:
            # Clear any existing code/data at this 4-byte slot
            clearListing(addr, _addr(addr_int + 3))
            # Create DWORD data
            du = listing.createData(addr, dt)
            if du is not None:
                nok += 1
            else:
                print("[warn] createData returned None @ 0x%08x" % addr_int)
                nfail += 1
        except Exception as e:
            print("[warn] createDWord @ 0x%08x: %s" % (addr_int, e))
            nfail += 1

    print("=== DONE: ok=%d fail=%d ===" % (nok, nfail))


main()
